# annotate-output
# Autogenerated from man page /usr/share/man/man1/annotate-output.1.gz
# using Deroffing man parser
complete -c annotate-output -s h -l help --description 'Display a help message and exit successfully.'

