# apt-src
# Autogenerated from man page /usr/share/man/man1/apt-src.1p.gz
# using Type1
complete -c apt-src -s h -l help --description 'Show this help text.'
complete -c apt-src -s b -l build -l compile --description 'Build source packages after installing or upgrading them.'
complete -c apt-src -s i -l installdebs --description 'Install packages after building sources.  Implies --build.'
complete -c apt-src -s p -l patch --description 'Try to patch local changes into new source tree when upgrading.'
complete -c apt-src -s l -l location --description 'Specify a directory; only operate on packages i… [See Man Page]'
complete -c apt-src -s c -l cwd -l here --description 'Only operate on packages in the current directory.'
complete -c apt-src -l upstream-version --description 'Only of use with the version command; makes it … [See Man Page]'
complete -c apt-src -s k -l keep-built --description 'Do not delete .'
complete -c apt-src -s n -l no-delete-source --description 'Do not delete source files when removing source package.'
complete -c apt-src -l version --description 'Specify a source tree version.  Of use with the import command.'
complete -c apt-src -s q -l quiet --description 'Direct all command output to /dev/null unless a… [See Man Page]'
complete -c apt-src -s t -l trace --description 'Output each command as it is run.'

