# apt-show-versions
# Autogenerated from man page /usr/share/man/man1/apt-show-versions.1p.gz
# using Type1
complete -c apt-show-versions -s p -l package --description 'Print available and installed versions for specified package.'
complete -c apt-show-versions -s r -l regex --description 'interpret package from option -p as a regex.'
complete -c apt-show-versions -s R -l regex-all --description 'like --regex, but also show matching packages w… [See Man Page]'
complete -c apt-show-versions -s u -l upgradeable --description 'Print only upgradeable packages.'
complete -c apt-show-versions -s a -l allversions --description 'Print all available versions of the selected packages.'
complete -c apt-show-versions -s b -l brief --description 'Print only package_name/distribution for upgradeable packages.'
complete -c apt-show-versions -s v -l verbose --description 'Prints out messages about which Package files are parsed.'
complete -c apt-show-versions -s i -l initialize --description 'Initialize or update package cache only (as root).'
complete -c apt-show-versions -o stf -l status-file --description 'Use file as the dpkg status file instead of /va… [See Man Page]'
complete -c apt-show-versions -o ld -l list-dir --description 'Use directory as path to apt\'s list files inste… [See Man Page]'

