# apt-file
# Autogenerated from man page /usr/share/man/man1/apt-file.1.gz
# using Type1
complete -c apt-file -s a -l architecture --description 'Sets architecture to architecture.'
complete -c apt-file -s c -l cache --description 'Sets the cache directory to cache-directory ins… [See Man Page]'
complete -c apt-file -s d -l cdrom-mount --description 'Use cdrom-mount-point instead of apt\'s.'
complete -c apt-file -s D -l from-deb --description 'Use contents of the given . deb archives(s) as patterns.'
complete -c apt-file -s f -l from-file --description 'Read patterns from the given file(s), one per line.'
complete -c apt-file -s F -l fixed-string --description 'Do not expand search pattern with generic chara… [See Man Page]'
complete -c apt-file -s i -l ignore-case --description 'Ignore case when searching for pattern.'
complete -c apt-file -s l -l package-only --description 'Only display package name; do not display file names.'
complete -c apt-file -s N -l non-interactive --description 'Skip schemes that are listed in the interactive… [See Man Page]'
complete -c apt-file -s s -l sources-list --description 'Sets the sources.'
complete -c apt-file -s v -l verbose --description 'Run apt-file in verbose mode.'
complete -c apt-file -s x -l regexp --description 'Treat pattern as a (perl) regular expression.'
complete -c apt-file -s y -l dummy --description 'Run in dummy mode (no action).'

