# arandr
# Autogenerated from man page /usr/share/man/man1/arandr.1.gz
# using Deroffing man parser
complete -c arandr -l version --description 'show program\\(aqs version number and exit.'
complete -c arandr -s h -l help --description 'show this help message and exit.'
complete -c arandr -l randr-display --description 'Use D as display for xrandr (but still show the… [See Man Page]'
complete -c arandr -l force-version --description 'Even run with untested XRandR versions.'

