# autokey
# Autogenerated from man page /usr/share/man/man1/autokey.1.gz
# using Deroffing man parser
complete -c autokey -l help --description 'Show summary of options.'
complete -c autokey -s l -l verbose --description 'Enable verbose (debug) logging.'
complete -c autokey -s c -l configure --description 'Show the configuration window on startup, even … [See Man Page]'

