# autokey-gtk
# Autogenerated from man page /usr/share/man/man1/autokey-gtk.1.gz
# using Deroffing man parser
complete -c autokey-gtk -l help --description 'Show summary of options.'
complete -c autokey-gtk -s l -l verbose --description 'Enable verbose (debug) logging.'
complete -c autokey-gtk -s c -l configure --description 'Show the configuration window on startup, even … [See Man Page]'

