# autokey-run
# Autogenerated from man page /usr/share/man/man1/autokey-run.1.gz
# using Deroffing man parser
complete -c autokey-run -l help --description 'Show summary of options.'
complete -c autokey-run -s l -l script --description 'Run a script with the specified name.'
complete -c autokey-run -s c -l phrase --description 'Paste a phrase with the specified name.'
complete -c autokey-run -l folder --description 'Display a popup menu for the specified folder.'

