# awsetbg
# Autogenerated from man page /usr/share/man/man1/awsetbg.1.gz
# using Deroffing man parser
complete -c awsetbg -s f --description 'Set fullscreen wallpaper.'
complete -c awsetbg -s c --description 'Set centered wallpaper.'
complete -c awsetbg -s t --description 'Set tiled wallpaper.'
complete -c awsetbg -s a --description 'Set maximized wallpaper, preserving the aspect ratio.'
complete -c awsetbg -s u --description 'Use the specified wallpaper setter tool.'
complete -c awsetbg -s r --description 'Set a random wallpaper from this directory.'
complete -c awsetbg -s F -s C -s T -s A -s U -s R --description 'Same as the lowercase options, but without remembering.'
complete -c awsetbg -s l --description 'Set the previous wallpaper.'
complete -c awsetbg -s i --description 'Display useful information about the best appli… [See Man Page]'
complete -c awsetbg -s m --description 'Use montage to create a big image (image should… [See Man Page]'
complete -c awsetbg -s p --description 'Display useful tips.'
complete -c awsetbg -s h --description 'Display help message.'

