# bin2obj-2
# Autogenerated from man page /usr/share/man/man1/bin2obj-2.6.0.1.gz
# using Deroffing man parser
complete -c bin2obj-2 -s a --description 'Write ASCII data instead of bytes.'
complete -c bin2obj-2 -s e --description 'If this option is given, the data will be encry… [See Man Page]'
complete -c bin2obj-2 -s h --description 'emit a small helptext.'
complete -c bin2obj-2 -s o --description 'By default, the output goes to standard output (the screen).'
complete -c bin2obj-2 -s u --description 'This option tells  bin2obj to generate a unit.'
complete -c bin2obj-2 -s U --description 'The same as the  -u option, only bin2obj will a… [See Man Page]'
complete -c bin2obj-2 -s c --description 'option).  The output goes to standard output by default.'
complete -c bin2obj-2 -s z --description 'Compress the data before creating the unit.'

