# chdist
# Autogenerated from man page /usr/share/man/man1/chdist.1.gz
# using Type1
complete -c chdist -s h -l help --description 'Provide a usage message.'
complete -c chdist -s d -l data-dir --description 'Choose data directory (default: \\f(CI$HOME/. chdist/).'
complete -c chdist -s a -l arch --description 'Choose architecture (default: `dpkg --print-architecture`).'

