# checkbashisms
# Autogenerated from man page /usr/share/man/man1/checkbashisms.1.gz
# using Deroffing man parser
complete -c checkbashisms -l help -s h --description 'Show a summary of options.'
complete -c checkbashisms -l newline -s n --description 'Check for "echo -n" usage (non POSIX but requir… [See Man Page]'
complete -c checkbashisms -l posix -s p --description 'Check for issues which are non POSIX but requir… [See Man Page]'
complete -c checkbashisms -l force -s f --description 'Force each script to be checked, even if it wou… [See Man Page]'
complete -c checkbashisms -l extra -s x --description 'Highlight lines which, whilst they do not conta… [See Man Page]'
complete -c checkbashisms -l version -s v --description 'Show version and copyright information.'

