# chsh
# Autogenerated from man page /usr/share/man/man1/chsh.1.gz
# using Deroffing man parser
complete -c chsh -s h -l help --description 'Display help message and exit.'
complete -c chsh -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c chsh -s s -l shell --description 'The name of the user\\*(Aqs new login shell.'

