# cli-resgen
# Autogenerated from man page /usr/share/man/man1/cli-resgen.1.gz
# using Deroffing man parser
complete -c cli-resgen -o compile --description 'Sp This switch instructs resgen to compile multiple files.'
complete -c cli-resgen -o usesourcepath --description '.'

