# clojure
# Autogenerated from man page /usr/share/man/man1/clojure.1.gz
# using Deroffing man parser
complete -c clojure -o cp -o classpath --description 'Specifies additional classpath elements.'
complete -c clojure -s i -l init --description 'Load a file or resource at initialisation time.'
complete -c clojure -s e -l eval --description 'Evaluate expressions in string; print non-nil values.'
complete -c clojure -s r -l repl --description 'Run a repl.'
complete -c clojure -s h -s '?' -l help --description 'Print a help message and exit PATH ARGUMENTS A … [See Man Page]'

