# clojurec
# Autogenerated from man page /usr/share/man/man1/clojurec.1.gz
# using Deroffing man parser
complete -c clojurec -s d --description 'Specifies the destination directory for compiled class files.'
complete -c clojurec -s W -o Wreflect --description 'Causes the compiler to emit warnings when refle… [See Man Page]'
complete -c clojurec -o cp -o classpath --description 'Specifies additional classpath elements.'

