# collateindex
# Autogenerated from man page /usr/share/man/man1/collateindex.pl.1.gz
# using Type1
complete -c collateindex -s f --description 'Force the output file to be written, even if it… [See Man Page]'
complete -c collateindex -s g --description 'Group terms with IndexDiv based on the first le… [See Man Page]'
complete -c collateindex -s i --description 'The \\s-1ID\\s0 to use for the <index> tag.'
complete -c collateindex -s I --description 'The implied scope, must be \\f(CW\\*(C`all\\*(C\', … [See Man Page]'
complete -c collateindex -s N --description 'New index (generates an empty index file).'
complete -c collateindex -s o --description 'Output to file.  Defaults to stdout.'
complete -c collateindex -s p --description 'Link to points in the document.'
complete -c collateindex -s P --description 'Read a preamble from file.'
complete -c collateindex -s q --description 'Run quietly.'
complete -c collateindex -s s --description 'Name the IndexDiv that contains symbols.'
complete -c collateindex -s S --description 'Scope of the index, must be \\f(CW\\*(C`all\\*(C\',… [See Man Page]'
complete -c collateindex -s t --description 'Title for the index.'
complete -c collateindex -s x --description 'Make a SetIndex.'
complete -c collateindex -s V --description 'Print version number and exit.'

