# cvs-debrelease
# Autogenerated from man page /usr/share/man/man1/cvs-debrelease.1.gz
# using Deroffing man parser
complete -c cvs-debrelease -l dupload -l dput --description 'This specifies which uploader program to use; t… [See Man Page]'
complete -c cvs-debrelease -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c cvs-debrelease -o Mmodule --description 'The name of the CVS module.'
complete -c cvs-debrelease -o Ppackage --description 'The name of the package.'
complete -c cvs-debrelease -o Vversion --description 'The version number of the package.'
complete -c cvs-debrelease -o Ttag --description 'The CVS tag to use for exporting sources.'
complete -c cvs-debrelease -o Rrootdirectory --description 'Root of the original sources archive.'
complete -c cvs-debrelease -o Wwork --description 'The full path name for the cvs-buildpackage working directory.'
complete -c cvs-debrelease -o xprefix --description 'This option provides the CVS default module prefix.'
complete -c cvs-debrelease -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c cvs-debrelease -o Rroot --description 'Root of the original sources archive.'
complete -c cvs-debrelease -l help -l version --description 'Show help message and version information respectively.'

