# debcommit
# Autogenerated from man page /usr/share/man/man1/debcommit.1.gz
# using Type1
complete -c debcommit -s c -l changelog --description 'Specify an alternate location for the changelog.'
complete -c debcommit -s r -l release --description 'Commit a release of the package.'
complete -c debcommit -s R -l release-use-changelog --description 'When used in conjunction with --release, if the… [See Man Page]'
complete -c debcommit -s m -l message --description 'Specify a commit message to use.'
complete -c debcommit -s n -l noact --description 'Do not actually do anything, but do print the c… [See Man Page]'
complete -c debcommit -s d -l diff --description 'Instead of committing, do print the diff of wha… [See Man Page]'
complete -c debcommit -s C -l confirm --description 'Display the generated commit message and ask fo… [See Man Page]'
complete -c debcommit -s e -l edit --description 'Edit the generated commit message in your favor… [See Man Page]'
complete -c debcommit -s a -l all --description 'Commit all files.'
complete -c debcommit -s s -l strip-message -l no-strip-message --description 'If this option is set and the commit message ha… [See Man Page]'

