# debcheckout
# Autogenerated from man page /usr/share/man/man1/debcheckout.1.gz
# using Type1
complete -c debcheckout -s a -l auth --description 'Work in authenticated mode; this means that for… [See Man Page]'
complete -c debcheckout -s d -l details --description 'Only print a list of detailed information about… [See Man Page]'
complete -c debcheckout -s h -l help --description 'Print a detailed help message and exit.'
complete -c debcheckout -s p -l print --description 'Only print a summary about package repository i… [See Man Page]'
complete -c debcheckout -s P -l package --description 'When checking out a repository \\s-1URL\\s0, inst… [See Man Page]'
complete -c debcheckout -s t -l type --description 'Override the repository type (which defaults to… [See Man Page]'
complete -c debcheckout -s u -l user --description 'Specify the login name to be used in authentica… [See Man Page]'
complete -c debcheckout -s f -l file --description 'Specify that the named file should be extracted… [See Man Page]'
complete -c debcheckout -l source --description 'Some packages only place the debian directory i… [See Man Page]'

