# debc
# Autogenerated from man page /usr/share/man/man1/debc.1.gz
# using Deroffing man parser
complete -c debc -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c debc -l debs-dir --description 'Look for the . changes, . deb and .'
complete -c debc -l check-dirname-level --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debc -l check-dirname-regex --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debc -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c debc -l help -l version --description 'Show help message and version information respectively.'

