# debsign
# Autogenerated from man page /usr/share/man/man1/debsign.1.gz
# using Deroffing man parser
complete -c debsign -s r --description 'The . changes and .'
complete -c debsign -o pprogname --description 'When debsign needs to execute GPG to sign it wi… [See Man Page]'
complete -c debsign -o mmaintainer --description 'Specify the maintainer name to be used for signing.'
complete -c debsign -o emaintainer --description 'Same as -m but takes precedence over it.'
complete -c debsign -o kkeyid --description 'Specify the key ID to be used for signing; over… [See Man Page]'
complete -c debsign -s S --description 'Look for a source-only .'
complete -c debsign -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c debsign -l multi --description 'Multiarch changes mode: This signifies that deb… [See Man Page]'
complete -c debsign -l re-sign -l no-re-sign --description 'Recreate signature, respectively use the existi… [See Man Page]'
complete -c debsign -l debs-dir --description 'Look for the . changes and .'
complete -c debsign -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c debsign -l help -s h --description 'Display a help message and exit successfully.'
complete -c debsign -l version --description 'Display version and copyright information and e… [See Man Page]'

