# debsnap
# Autogenerated from man page /usr/share/man/man1/debsnap.1.gz
# using Deroffing man parser
complete -c debsnap -s d -l destdir --description 'Directory to place retrieved packages.'
complete -c debsnap -s f -l force --description 'Force writing into an existing destination.'
complete -c debsnap -s v -l verbose --description 'Report on the debsnap configuration being used … [See Man Page]'
complete -c debsnap -l binary --description 'Download binary packages instead of source packages.'
complete -c debsnap -s a -l architecture --description 'Specify architecture of downloaded binary packages.'
complete -c debsnap -s h -l help --description 'Show a summary of these options.'
complete -c debsnap -l version --description 'Show the version of debsnap.'

