# debuild
# Autogenerated from man page /usr/share/man/man1/debuild.1.gz
# using Type1
complete -c debuild -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c debuild -l rootcmd -s r --description 'Command to gain root (or fake root) privileges.'
complete -c debuild -l preserve-env --description 'Do not clean the environment, except for PATH.'
complete -c debuild -l preserve-envvar -s e --description 'Do not clean the var variable from the environment.'
complete -c debuild -l set-envvar --description 'Set the environment variable var to value and d… [See Man Page]'
complete -c debuild -l prepend-path --description 'Once the normalized PATH has been set, prepend value to it.'
complete -c debuild -l lintian --description 'Run lintian after dpkg-buildpackage.'
complete -c debuild -l no-lintian --description 'Do not run lintian after dpkg-buildpackage.'
complete -c debuild -l no-tgz-check --description 'Even if we\'re running dpkg-buildpackage and the… [See Man Page]'
complete -c debuild -l tgz-check --description 'If we\'re running dpkg-buildpackage and the vers… [See Man Page]'
complete -c debuild -l username --description 'When signing, use debrsign instead of debsign.'
complete -c debuild -l foo-hook --description 'Set a hook as described above.'
complete -c debuild -l clear-hooks --description 'Clears all hooks.'
complete -c debuild -l check-dirname-level --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debuild -l check-dirname-regex --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debuild -s d --description 'Do not run dpkg-checkbuilddeps to check build dependencies.'

