# defoma-font
# Autogenerated from man page /usr/share/man/man1/defoma-font.1.gz
# using Deroffing man parser
complete -c defoma-font -s t --description 'Exit with true value (0) even if error occurs.'
complete -c defoma-font -s v --description 'Verbose output.'
complete -c defoma-font -s d --description 'More verbose output.'
complete -c defoma-font -s q --description 'Quiet output.  EXAMPLES.'

