# defoma-app
# Autogenerated from man page /usr/share/man/man1/defoma-app.1.gz
# using Deroffing man parser
complete -c defoma-app -s t --description 'Exit with true value (0) even if error occurs.'
complete -c defoma-app -s v --description 'Verbose output.'
complete -c defoma-app -s d --description 'Debug/Testing mode.'
complete -c defoma-app -s q --description 'Quiet output.  SEE ALSO defoma (1).'

