# defoma-hints
# Autogenerated from man page /usr/share/man/man1/defoma-hints.1.gz
# using Deroffing man parser
complete -c defoma-hints -s c --description 'Force text interface, even if $DISPLAY is set.'
complete -c defoma-hints -l no-question --description 'Accept default hint choice without prompting.  FILES.'

