# delp-2
# Autogenerated from man page /usr/share/man/man1/delp-2.6.0.1.gz
# using Deroffing man parser
complete -c delp-2 -s e --description 'Delete all executable files as well.'
complete -c delp-2 -s h --description 'Displays a short help message.'
complete -c delp-2 -s q --description 'Be more quiet.'

