# delp
# Autogenerated from man page /usr/share/man/man1/delp.1.gz
# using Deroffing man parser
complete -c delp -s e --description 'Delete all executable files as well.'
complete -c delp -s h --description 'Displays a short help message.'
complete -c delp -s q --description 'Be more quiet.'

