# dep3changelog
# Autogenerated from man page /usr/share/man/man1/dep3changelog.1.gz
# using Deroffing man parser
complete -c dep3changelog -l help -s h --description 'Display a help message and exit successfully.'
complete -c dep3changelog -l version --description 'Display version and copyright information and e… [See Man Page]'

