# dh_javadoc
# Autogenerated from man page /usr/share/man/man1/dh_javadoc.1.gz
# using Type1
complete -c dh_javadoc -l sourcedir --description 'Specify the source path in which to look for Java source files.'

