# dh_nativejava
# Autogenerated from man page /usr/share/man/man1/dh_nativejava.1.gz
# using Type1
complete -c dh_nativejava -s n -l noscripts --description 'Do not modify postinst/postrm scripts.'
complete -c dh_nativejava -s o -l onlyscripts --description 'Only modify postinst/postrm scripts, do not act… [See Man Page]'

