# directfb-csource
# Autogenerated from man page /usr/share/man/man1/directfb-csource.1.gz
# using Deroffing man parser
complete -c directfb-csource -l name --description 'Specifies the identifier name (prefix) for the … [See Man Page]'
complete -c directfb-csource -l format --description 'Specifies the pixel-format of the generated inline surface.'
complete -c directfb-csource -l version --description 'Output version information.'
complete -c directfb-csource -l help --description 'Print brief help and exit.'

