# dpkg-checkbuilddeps
# Autogenerated from man page /usr/share/man/man1/dpkg-checkbuilddeps.1.gz
# using Deroffing man parser
complete -c dpkg-checkbuilddeps -l admindir --description 'Change the location of the dpkg database.'
complete -c dpkg-checkbuilddeps -s A --description 'Ignore Build-Depends-Arch and Build-Conflicts-Arch lines.'
complete -c dpkg-checkbuilddeps -s B --description 'Ignore Build-Depends-Indep and Build-Conflicts-Indep lines.'
complete -c dpkg-checkbuilddeps -s c --description 'Use the given build dependencies/conflicts inst… [See Man Page]'
complete -c dpkg-checkbuilddeps -s a --description 'Check build dependencies/conflicts assuming tha… [See Man Page]'
complete -c dpkg-checkbuilddeps -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-checkbuilddeps -s d --description '.'
complete -c dpkg-checkbuilddeps -l version --description 'Show the version and exit.'

