# dpkg-depcheck
# Autogenerated from man page /usr/share/man/man1/dpkg-depcheck.1.gz
# using Deroffing man parser
complete -c dpkg-depcheck -s a -l all --description 'Report all packages used to run command.'
complete -c dpkg-depcheck -s b -l build-depends --description 'Do not report any build-essential or essential … [See Man Page]'
complete -c dpkg-depcheck -s d -l ignore-dev-deps --description 'Do not show packages used which are direct depe… [See Man Page]'
complete -c dpkg-depcheck -s m -l min-deps --description 'Output a minimal set of packages needed, taking… [See Man Page]'
complete -c dpkg-depcheck -s C -l C-locale --description 'Run command with the C locale.'
complete -c dpkg-depcheck -l no-C-locale --description 'Don\'t change locale when running command.'
complete -c dpkg-depcheck -s l -l list-files --description 'Also report the list of files used in each package.'
complete -c dpkg-depcheck -l no-list-files --description 'Do not report the files used in each package.'
complete -c dpkg-depcheck -s o -l output --description 'Output the package diagnostics to FILE instead of stdout.'
complete -c dpkg-depcheck -s O -l strace-output --description 'Write the strace output to FILE when tracing co… [See Man Page]'
complete -c dpkg-depcheck -s I -l strace-input --description 'Get strace output from FILE instead of tracing … [See Man Page]'
complete -c dpkg-depcheck -s f -l features --description 'Enable or disabled features given in the comma-… [See Man Page]'
complete -c dpkg-depcheck -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c dpkg-depcheck -s h -l help --description 'Display usage information and exit.'
complete -c dpkg-depcheck -s v -l version --description 'Display version and copyright information and exit.'

