# dpkg-ruby
# Autogenerated from man page /usr/share/man/man1/dpkg-ruby.1.gz
# using Deroffing man parser
complete -c dpkg-ruby -l file --description 'PD The file to parse.   The default is /var/lib/dpkg/status.'
complete -c dpkg-ruby -l debug --description 'PD Each time this is specified, it increased the debug level.'
complete -c dpkg-ruby -l sort --description 'PD A space or comma separated list of fields to sort on.'
complete -c dpkg-ruby -l numeric --description 'PD A space or comma separated list of fields th… [See Man Page]'
complete -c dpkg-ruby -l rec_sep --description 'PD Output this string at the end of each output paragraph. \\".'
complete -c dpkg-ruby -l outform --description '\\" . PD . \\" Specify the outform that dpkg-ruby should use.'
complete -c dpkg-ruby -l help --description 'PD Display some help.'
complete -c dpkg-ruby -s f --description '.'
complete -c dpkg-ruby -s d --description '.'
complete -c dpkg-ruby -s s --description '.'
complete -c dpkg-ruby -s n --description '.'
complete -c dpkg-ruby -o rs --description '.'
complete -c dpkg-ruby -s h --description '.'

