# dselect
# Autogenerated from man page /usr/share/man/man1/dselect.1.gz
# using Deroffing man parser
complete -c dselect -l admindir --description 'Changes the directory where the dpkg `status\', … [See Man Page]'
complete -c dselect -l debug -s D --description 'Turn on debugging.  Debugging information is sent to file.'
complete -c dselect -l expert --description 'Turns on expert mode, i. e.'
complete -c dselect -l colour -l color --description 'Configures screen colors.'
complete -c dselect -l help --description 'Print a brief help text and exit successfully.'
complete -c dselect -l version --description 'Print version information and exit successfully.'

