# erlang-depends
# Autogenerated from man page /usr/share/man/man1/erlang-depends.1.gz
# using Type1
complete -c erlang-depends -s v -l verbose --description 'Verbose mode.'
complete -c erlang-depends -s a -l arch --description 'Act on all architecture dependent packages.'
complete -c erlang-depends -s i -l indep --description 'Act on all architecture independent packages.'
complete -c erlang-depends -o ppackage -l package --description 'Act on the package named \\*(L"package\\*(R".'
complete -c erlang-depends -o Npackage -l no-package --description 'Do not act on the specified package even if an … [See Man Page]'
complete -c erlang-depends -l ignore --description 'Ignore the specified file.'

