# evrouter
# Autogenerated from man page /usr/share/man/man1/evrouter.1.gz
# using Deroffing man parser
complete -c evrouter -s c -l config --description 'Read the rules from CONFIG-FILE instead of the default, $HOME/.'
complete -c evrouter -s D -l devices --description 'Opens all event interface devices specified, qu… [See Man Page]'
complete -c evrouter -s d -l dump --description 'Dump mode.'
complete -c evrouter -s f -l foreground --description 'Do not run in the background.  Useful for testing.'
complete -c evrouter -s q -l quit --description 'Kill the running daemon, then exit.'
complete -c evrouter -s v -l verbose --description 'Increase the verbosity of the program.'
complete -c evrouter -s '?' -l help --description 'List all available options and their meanings.'
complete -c evrouter -l usage --description 'Display brief usage information.'
complete -c evrouter -s V -l version --description 'Show the program\'s version, credits and licensing.'
complete -c evrouter -o 'd.' --description 'the following rules will be interpreted.'

