# extundelete
# Autogenerated from man page /usr/share/man/man1/extundelete.1.gz
# using Deroffing man parser
complete -c extundelete -l version --description 'Prints the version number of extundelete.'
complete -c extundelete -l help --description 'Print a brief usage summary for extundelete.'
complete -c extundelete -l superblock --description 'Prints information about the filesystem from the superblock.'
complete -c extundelete -l journal --description 'Prints information about the journal from the j… [See Man Page]'
complete -c extundelete -l inode --description 'Prints the information from the inode number of… [See Man Page]'
complete -c extundelete -l block --description 'Prints the contents of the block, called as "--block 9652".'
complete -c extundelete -l restore-file --description 'Attempts to restore the file which was deleted … [See Man Page]'
complete -c extundelete -l restore-inode --description 'Used to restore inodes by number, called as "--… [See Man Page]'
complete -c extundelete -l restore-files --description 'Restores a list of files.'
complete -c extundelete -l output-dir --description 'Restores files in the output dir \'path\'.'
complete -c extundelete -l restore-all --description 'Restores all files possible to undelete to thei… [See Man Page]'
complete -c extundelete -l restore-directory --description 'Restores all files possible to link to specifie… [See Man Page]'
complete -c extundelete -s j --description 'Specifies the device that is the external journ… [See Man Page]'
complete -c extundelete -s b --description 'Specifies the block number of the backup superb… [See Man Page]'
complete -c extundelete -s B --description 'Specifies the block size of the partition to be… [See Man Page]'
complete -c extundelete -l before --description 'Only restore files deleted before the date spec… [See Man Page]'
complete -c extundelete -l after --description 'Only restore files deleted after the date speci… [See Man Page]'

