# fd2pascal-2
# Autogenerated from man page /usr/share/man/man1/fd2pascal-2.6.0.1.gz
# using Deroffing man parser
complete -c fd2pascal-2 -o altformat --description 'By default, a record type is emitted for the fo… [See Man Page]'
complete -c fd2pascal-2 -o compensate --description 'If this option is given then a call to fl_adjus… [See Man Page]'
complete -c fd2pascal-2 -o callback --description 'If this option is given, then a callback proced… [See Man Page]'
complete -c fd2pascal-2 -o main --description 'By default, a unit is created which can be incl… [See Man Page]'

