# fmtutil-sys
# Autogenerated from man page /usr/share/man/man1/fmtutil-sys.1.gz
# using Type1
complete -c fmtutil-sys -l cnffile --description 'specify the configuration file fmtutil should use.'
complete -c fmtutil-sys -l dolinks --description '(not implemented, just for compatibility).'
complete -c fmtutil-sys -l fmtdir --description 'set the destination directory for format files … [See Man Page]'
complete -c fmtutil-sys -l force --description '(not implemented, just for compatibility).'
complete -c fmtutil-sys -l no-engine-subdir --description 'don\'t use engine-specific subdir of the fmtdir.'
complete -c fmtutil-sys -l no-error-if-no-format --description 'exit successfully if no format is selected.'
complete -c fmtutil-sys -l quiet --description 'be silent.'

