# fontforge
# Autogenerated from man page /usr/share/man/man1/fontforge.1.gz
# using Deroffing man parser
complete -c fontforge -s c --description 'Must be the first argument.'
complete -c fontforge -o cmap --description 'Employ the specified method to control 8-bit co… [See Man Page]'
complete -c fontforge -o depth --description 'Attempt to employ a visual that matches the spe… [See Man Page]'
complete -c fontforge -o display --description 'Employ the X display specified by the string  s… [See Man Page]'
complete -c fontforge -o help --description 'Display the usage description and start a web c… [See Man Page]'
complete -c fontforge -o keyboard --description 'Alter the displayed menus to employ modifier ke… [See Man Page]'
complete -c fontforge -o last --description 'Opens whatever font you last edited with  fontforge.'
complete -c fontforge -o lang --description 'Interpret the script with the fontforge interpreter.'
complete -c fontforge -o library-status --description 'Prints information about optional libraries.'
complete -c fontforge -o new --description 'Create a new font with the ISO 8859-1 encoding … [See Man Page]'
complete -c fontforge -o nosplash --description 'Suppress display of the splash screen.'
complete -c fontforge -o recover --description 'Control the crash recovery mechanism (helpful i… [See Man Page]'
complete -c fontforge -o script --description 'Execute the script named R file .  Does not open the X display.'
complete -c fontforge -o sync --description 'Make X synchronous.'
complete -c fontforge -o usage --description 'Display the usage description.'
complete -c fontforge -o vc --description 'Attempt to use a visual that matches the class,… [See Man Page]'
complete -c fontforge -o version --description 'Display the current version (a six digit string… [See Man Page]'
complete -c fontforge -o man --description '.'

