# fpcmake-2
# Autogenerated from man page /usr/share/man/man1/fpcmake-2.6.0.1.gz
# using Deroffing man parser
complete -c fpcmake-2 -s h --description 'Emit a short help text describing the use of  fpcmake.'
complete -c fpcmake-2 -s p --description 'If this option is given, a package description … [See Man Page]'
complete -c fpcmake-2 -s q --description 'Tells   fpcmake to be more quiet, i. e.  emit less messages.'
complete -c fpcmake-2 -s r --description 'If this option is given,   fpcmake will recursi… [See Man Page]'
complete -c fpcmake-2 -s T --description 'Specifies the targets for which   fpcmake  shou… [See Man Page]'
complete -c fpcmake-2 -s v --description 'This option instructs  fpcmake to be more verbose.'
complete -c fpcmake-2 -s V --description 'Print  fpcmake version and exit.'
complete -c fpcmake-2 -s w --description 'This is the standard option and tells fpcmake t… [See Man Page]'

