# fprcp
# Autogenerated from man page /usr/share/man/man1/fprcp.1.gz
# using Deroffing man parser
complete -c fprcp -s C --description 'Define the symbol   symbol before processing is started.'
complete -c fprcp -s i --description 'Specify the input file name.  This argument is mandatory.'
complete -c fprcp -s l --description 'Set the programming language for include files.'
complete -c fprcp -s n --description 'Do not support nested comments.'
complete -c fprcp -s p --description 'Set the include path.'

