# freetype-config
# Autogenerated from man page /usr/share/man/man1/freetype-config.1.gz
# using Type1
complete -c freetype-config -l prefix -l prefix --description 'Show the prefix freetype2 was built with.'
complete -c freetype-config -l exec-prefix -l exec-prefix --description 'Show the executable prefix freetype2 was built with.'
complete -c freetype-config -l version --description 'Show the libtool version of the installed freetype2.'
complete -c freetype-config -l ftversion --description 'Show the FreeType version of the installed freetype2.'
complete -c freetype-config -l libs --description 'Show the compiler flags for linking to the installed freetype2.'
complete -c freetype-config -l libtool --description 'Show the library name for linking with libtool.'

