# gappletviewer
# Autogenerated from man page /usr/share/man/man1/gappletviewer.1.gz
# using Type1
complete -c gappletviewer -o debug --description 'This option is not yet implemented but is provi… [See Man Page]'
complete -c gappletviewer -o encoding --description 'Use this option to specify an alternate charact… [See Man Page]'
complete -c gappletviewer -o code --description 'Use the -code option to specify the value of th… [See Man Page]'
complete -c gappletviewer -o codebase --description 'Use the -codebase option to specify the value o… [See Man Page]'
complete -c gappletviewer -o archive --description 'Use the -archive option to specify the value of… [See Man Page]'
complete -c gappletviewer -o width --description 'Use the -width option to specify the value of t… [See Man Page]'
complete -c gappletviewer -o height --description 'Use the -height option to specify the value of … [See Man Page]'
complete -c gappletviewer -o param --description 'Use the -param option to specify values for the… [See Man Page]'
complete -c gappletviewer -o plugin --description 'gcjwebplugin uses the -plugin option to specify… [See Man Page]'
complete -c gappletviewer -o verbose --description 'Use the -verbose option to have the appletviewe… [See Man Page]'
complete -c gappletviewer -o help --description 'Use the -help option to have the appletviewer p… [See Man Page]'
complete -c gappletviewer -o version --description 'Use the -version option to have the appletviewe… [See Man Page]'

