# gdbserver
# Autogenerated from man page /usr/share/man/man1/gdbserver.1.gz
# using Deroffing man parser
complete -c gdbserver -l baud --description 'Ie: `gdb TARGET-PROG\', or `gdb --baud BAUD TARGET-PROG\'.'

