# gjar-4
# Autogenerated from man page /usr/share/man/man1/gjar-4.7.1.gz
# using Type1
complete -c gjar-4 -s c --description 'Create new archive.'
complete -c gjar-4 -s t --description 'List table of contents for archive.'
complete -c gjar-4 -s x --description 'Extract named (or all) files from archive.'
complete -c gjar-4 -s u --description 'Update existing archive.'
complete -c gjar-4 -s i --description 'Compute archive index. PP Operation modifiers:.'
complete -c gjar-4 -s f --description 'Specify archive file name.'
complete -c gjar-4 -s 0 --description 'Store only; use no \\s-1ZIP\\s0 compression.'
complete -c gjar-4 -s v --description 'Generate verbose output on standard output.'
complete -c gjar-4 -s M --description 'Do not create a manifest file for the entries.'
complete -c gjar-4 -s m --description 'Include manifest information from specified manifest file.'
complete -c gjar-4 -s C --description 'Change to the \\s-1DIR\\s0 and include the following \\s-1FILE\\s0.'
complete -c gjar-4 -s @ --description 'Read the names of the files to add to the archive from stdin.'
complete -c gjar-4 -o help --description 'Print help text, then exit.'
complete -c gjar-4 -o version --description 'Print version number, then exit.'

