# gjarsigner
# Autogenerated from man page /usr/share/man/man1/gjarsigner.1.gz
# using Type1
complete -c gjarsigner -o verbose --description 'Use this option to force the tool to generate m… [See Man Page]'
complete -c gjarsigner -o internalsf --description 'When present, the tool will include --which oth… [See Man Page]'
complete -c gjarsigner -o sectionsonly --description 'When present, the tool will include in the \\f(CW\\*(C`.'
complete -c gjarsigner -o provider --description 'A fully qualified class name of a Security Prov… [See Man Page]'
complete -c gjarsigner -o help --description 'Prints a help text similar to this one. PP Signing options  .'
complete -c gjarsigner -o keystore --description 'Use this option to specify the location of the … [See Man Page]'
complete -c gjarsigner -o storetype --description 'Use this option to specify the type of the key store to use.'
complete -c gjarsigner -o storepass --description 'Use this option to specify the password which w… [See Man Page]'
complete -c gjarsigner -o keypass --description 'Use this option to specify the password which t… [See Man Page]'
complete -c gjarsigner -o sigfile --description 'Use this option to designate a literal that wil… [See Man Page]'
complete -c gjarsigner -o signedjar --description 'Use this option to specify the file name of the… [See Man Page]'
complete -c gjarsigner -o verify --description 'Use this option to indicate that the tool is to… [See Man Page]'

