# gjavah-4
# Autogenerated from man page /usr/share/man/man1/gjavah-4.7.1.gz
# using Type1
complete -c gjavah-4 -s d --description 'Set output directory.'
complete -c gjavah-4 -s o --description 'Set output file (only one of -d or -o may be used).'
complete -c gjavah-4 -o cmdfile --description 'Read command file.'
complete -c gjavah-4 -o all --description 'Operate on all class files under directory \\s-1DIR\\s0.'
complete -c gjavah-4 -o stubs --description 'Emit stub implementation.'
complete -c gjavah-4 -o jni --description 'Emit \\s-1JNI\\s0 stubs or header (default).'
complete -c gjavah-4 -o cni --description 'Emit \\s-1CNI\\s0 stubs or header (default \\s-1JNI\\s0).'
complete -c gjavah-4 -o verbose --description 'Set verbose mode.'
complete -c gjavah-4 -o force --description 'Output files should always be written. PP Class path options:.'
complete -c gjavah-4 -o classpath --description 'Set the class path.'
complete -c gjavah-4 -o 'I\\s-1DIR\\s0' --description 'Add directory to class path.'
complete -c gjavah-4 -o bootclasspath --description 'Set the boot class path.'
complete -c gjavah-4 -o extdirs --description 'Set the extension directory path. PP Standard options:.'
complete -c gjavah-4 -o help --description 'Print help text, then exit.'
complete -c gjavah-4 -o version --description 'Print version number, then exit.'

