# gnative2ascii-4
# Autogenerated from man page /usr/share/man/man1/gnative2ascii-4.7.1.gz
# using Type1
complete -c gnative2ascii-4 -o encoding --description 'Set the encoding to use.'
complete -c gnative2ascii-4 -o reversed --description 'Convert from encoding to native. PP Standard options:.'
complete -c gnative2ascii-4 -o help --description 'Print help text, then exit.'
complete -c gnative2ascii-4 -o version --description 'Print version number, then exit.'

