# gnative2ascii
# Autogenerated from man page /usr/share/man/man1/gnative2ascii.1.gz
# using Type1
complete -c gnative2ascii -o encoding --description 'Set the encoding to use.'
complete -c gnative2ascii -o reversed --description 'Convert from encoding to native. PP Standard options:.'
complete -c gnative2ascii -o help --description 'Print help text, then exit.'
complete -c gnative2ascii -o version --description 'Print version number, then exit.'

