# go-clean
# Autogenerated from man page /usr/share/man/man1/go-clean.1.gz
# using Deroffing man parser
complete -c go-clean -s i --description 'The -i flag causes clean to remove the correspo… [See Man Page]'
complete -c go-clean -s n --description 'The -n flag causes clean to print the remove co… [See Man Page]'
complete -c go-clean -s r --description 'The -r flag causes clean to be applied recursiv… [See Man Page]'
complete -c go-clean -s x --description 'The -x flag causes clean to print remove comman… [See Man Page]'

