# go-list
# Autogenerated from man page /usr/share/man/man1/go-list.1.gz
# using Deroffing man parser
complete -c go-list -s f --description 'The -f flag specifies an alternate format for t… [See Man Page]'
complete -c go-list -o json --description 'The -json flag causes the package data to be pr… [See Man Page]'
complete -c go-list -s e --description 'The -e flag changes the handling of erroneous p… [See Man Page]'

