# godoc
# Autogenerated from man page /usr/share/man/man1/godoc.1.gz
# using Deroffing man parser
complete -c godoc -s v --description 'verbose mode.'
complete -c godoc -s q --description 'arguments are considered search queries: a lega… [See Man Page]'
complete -c godoc -o src --description 'print (exported) source in command-line mode.'
complete -c godoc -o tabwidth --description 'width of tabs in units of spaces.'
complete -c godoc -o timestamps --description 'show timestamps with directory listings.'
complete -c godoc -o index --description 'enable identifier and full text search index (n… [See Man Page]'
complete -c godoc -o index_files --description 'glob pattern specifying index files; if not emp… [See Man Page]'
complete -c godoc -o index_throttle --description 'index throttle value; a value of 0 means no tim… [See Man Page]'
complete -c godoc -o write_index --description 'write index to a file; the file name must be sp… [See Man Page]'
complete -c godoc -o maxresults --description 'maximum number of full text search results show… [See Man Page]'
complete -c godoc -o path --description 'additional package directories (colon-separated).'
complete -c godoc -o html --description 'print HTML in command-line mode.'
complete -c godoc -o goroot --description 'Go root directory.'
complete -c godoc -o http --description 'HTTP service address (e. g. , \'127. 0. 0.'
complete -c godoc -o server --description 'webserver address for command line searches.'
complete -c godoc -o templates --description 'directory containing alternate template files; … [See Man Page]'
complete -c godoc -o url --description 'print to standard output the data that would be… [See Man Page]'
complete -c godoc -o zip --description 'zip file providing the file system to serve; disabled if empty.'

