# gorbd
# Autogenerated from man page /usr/share/man/man1/gorbd.1.gz
# using Type1
complete -c gorbd -o ORBInitialPort --description 'Port on which persistent naming service is to be started.'
complete -c gorbd -o ior --description 'File in which to store persistent naming servic… [See Man Page]'
complete -c gorbd -o directory --description 'Directory in which to store persistent data.'
complete -c gorbd -o restart --description 'Restart persistent naming service, clearing per… [See Man Page]'
complete -c gorbd -o help --description 'Print help text, then exit.'
complete -c gorbd -o version --description 'Print version number, then exit.'

