# gpsdecode
# Autogenerated from man page /usr/share/man/man1/gpsdecode.1.gz
# using Deroffing man parser
complete -c gpsdecode -s d --description 'option tells the program to decode packets pres… [See Man Page]'
complete -c gpsdecode -s j --description 'explicitly sets the output dump format to JSON … [See Man Page]'
complete -c gpsdecode -s e --description 'option option tells the program to encode JSON … [See Man Page]'
complete -c gpsdecode -s t --description 'accepts a comma-separated list of numeric types.'
complete -c gpsdecode -s u --description 'suppresses scaling of AIS data to float quantit… [See Man Page]'
complete -c gpsdecode -s v --description 'enables dumping of textual packets to output as… [See Man Page]'
complete -c gpsdecode -s c --description 'sets the AIS dump format to separate fields wit… [See Man Page]'
complete -c gpsdecode -s V --description 'option directs the program to emit its version … [See Man Page]'
complete -c gpsdecode -s D --description 'option sets a debug verbosity level.'

