# gpsfake
# Autogenerated from man page /usr/share/man/man1/gpsfake.1.gz
# using Deroffing man parser
complete -c gpsfake -s b --description 'enables a twirling-baton progress indicator on standard error.'
complete -c gpsfake -s c --description 'sets the delay between sentences in seconds.'
complete -c gpsfake -s l --description 'makes the program dump a line or packet number … [See Man Page]'
complete -c gpsfake -s i --description 'is for single-stepping through logfiles.'
complete -c gpsfake -s m --description 'specifies a monitor program inside which the da… [See Man Page]'
complete -c gpsfake -s g --description 'uses the monitor facility to run the gpsd insta… [See Man Page]'
complete -c gpsfake -s f --description 'configures gpsd to bind to a random dynamic/pri… [See Man Page]'
complete -c gpsfake -s o --description 'specifies options to pass to the daemon.'
complete -c gpsfake -s D --description 'passes a -D option to the daemon: thus -D 4 is … [See Man Page]'
complete -c gpsfake -s r --description 'specifies an initialization command to use in pipe mode.'
complete -c gpsfake -s s --description 'sets the baud rate for the slave tty.  The default is 4800.'
complete -c gpsfake -s u --description 'forces the test framework to use UDP rather than pty devices.'
complete -c gpsfake -s v --description 'enables verbose progress reports to stderr.'
complete -c gpsfake -s x --description 'dumps packets as gpsfake gathers them.'
complete -c gpsfake -s h --description 'makes gpsfake print a usage message and exit.'

