# gpspipe
# Autogenerated from man page /usr/share/man/man1/gpspipe.1.gz
# using Deroffing man parser
complete -c gpspipe -s h --description 'gpspipe print a usage message and exit.'
complete -c gpspipe -s d --description 'gpspipe to run as a daemon.'
complete -c gpspipe -s l --description 'gpspipe to sleep for ten seconds before attempt… [See Man Page]'
complete -c gpspipe -s r --description '.'
complete -c gpspipe -s R --description '.'
complete -c gpspipe -s s --description 'gpspipe can be used with -s and -r options to e… [See Man Page]'
complete -c gpspipe -s o --description 'gpspipe is run as a daemon.'
complete -c gpspipe -s w --description 'gpsdsentences to be output.'
complete -c gpspipe -s t --description '.'
complete -c gpspipe -s T --description 'strftime(3) for the available placeholders.'
complete -c gpspipe -s p --description '.'
complete -c gpspipe -s n --description 'gpspipe will then exit gracefully.'
complete -c gpspipe -s v --description 'gpspipe to show a spinning activity indicator on stderr.'
complete -c gpspipe -s V --description '.'

