# grmid
# Autogenerated from man page /usr/share/man/man1/grmid.1.gz
# using Type1
complete -c grmid -o port --description 'Port on which activation system is to be started.'
complete -c grmid -o restart --description 'Restart activation system, clearing persistent … [See Man Page]'
complete -c grmid -o stop --description 'Stop activation system. PP Persistence:.'
complete -c grmid -o persistent --description 'Make activation system persistent.'
complete -c grmid -o directory --description 'Directory in which to store persistent data. PP Debugging:.'
complete -c grmid -o verbose --description 'Log binding events to standard out. PP Standard options:.'
complete -c grmid -o help --description 'Print help text, then exit.'
complete -c grmid -o version --description 'Print version number, then exit.'

