# grmiregistry
# Autogenerated from man page /usr/share/man/man1/grmiregistry.1.gz
# using Type1
complete -c grmiregistry -o restart --description 'Restart \\s-1RMI\\s0 naming service, clearing per… [See Man Page]'
complete -c grmiregistry -o stop --description 'Stop \\s-1RMI\\s0 naming service. PP Persistence:.'
complete -c grmiregistry -o persistent --description 'Make \\s-1RMI\\s0 naming service persistent.'
complete -c grmiregistry -o directory --description 'Directory in which to store persistent data. PP Debugging:.'
complete -c grmiregistry -o verbose --description 'Log binding events to standard out. PP Standard options:.'
complete -c grmiregistry -o help --description 'Print help text, then exit.'
complete -c grmiregistry -o version --description 'Print version number, then exit.'

