# gserialver
# Autogenerated from man page /usr/share/man/man1/gserialver.1.gz
# using Type1
complete -c gserialver -o classpath --description 'Class path to use to find classes. PP Standard options:.'
complete -c gserialver -o help --description 'Print help text, then exit.'
complete -c gserialver -o version --description 'Print version number, then exit.'

