# gtk-builder-convert
# Autogenerated from man page /usr/share/man/man1/gtk-builder-convert.1.gz
# using Deroffing man parser
complete -c gtk-builder-convert -l skip-windows -s w --description 'Convert everything but GtkWindow subclasses.'
complete -c gtk-builder-convert -l target-version -s t --description 'Some widgets and properties are different betwe… [See Man Page]'
complete -c gtk-builder-convert -l root -s r --description 'Convert only the widget named name and its children.'

