# gtnameserv
# Autogenerated from man page /usr/share/man/man1/gtnameserv.1.gz
# using Type1
complete -c gtnameserv -o ORBInitialPort --description 'Port on which naming service is to be started.'
complete -c gtnameserv -o ior --description 'File in which to store naming service\'s \\s-1IOR\\s0 reference.'
complete -c gtnameserv -o help --description 'Print help text, then exit.'
complete -c gtnameserv -o version --description 'Print version number, then exit.'

