# gtypist
# Autogenerated from man page /usr/share/man/man1/gtypist.1.gz
# using Deroffing man parser
complete -c gtypist -s b -l personal-best --description 'track personal best typing speeds.'
complete -c gtypist -s e -l max-error --description 'default maximum error percentage (default 3.'
complete -c gtypist -s n -l notimer --description 'turn off WPM timer in drills.'
complete -c gtypist -s t -l term-cursor --description 'use the terminal\'s hardware cursor.'
complete -c gtypist -s f -l curs-flash --description 'cursor flash period P*.'
complete -c gtypist -s c -l colours --description 'set initial display colours where available.'
complete -c gtypist -s s -l silent --description 'don\'t beep on errors.'
complete -c gtypist -s q -l quiet --description 'same as -s, --silent.'
complete -c gtypist -s l -l start-label --description 'start the lesson at label \'L\' .'
complete -c gtypist -s k -l no-skip --description 'forbid the user to skip exercises.'
complete -c gtypist -s i -l show-errors --description 'highlight errors with reverse video.'
complete -c gtypist -s h -l help --description 'print this message.'
complete -c gtypist -s v -l version --description 'output version information and exit.'
complete -c gtypist -s S -l always-sure --description 'do not ask confirmation questions.'
complete -c gtypist -l banner-colors --description 'package and version respectively).'
complete -c gtypist -s w -l word-processor --description '.'
complete -c gtypist -l scoring --description 'set scoring mode (words per minute or characters per minute).'

