# h2paspp-2
# Autogenerated from man page /usr/share/man/man1/h2paspp-2.6.0.1.gz
# using Deroffing man parser
complete -c h2paspp-2 -o dsymbol --description 'Define the symbol   symbol before processing is started.'
complete -c h2paspp-2 -s h --description 'emit a small helptext.'
complete -c h2paspp-2 -s I --description 'option was given, in which case the include fil… [See Man Page]'
complete -c h2paspp-2 -s o --description 'option is given, in which case the file is writ… [See Man Page]'
complete -c h2paspp-2 -o ooutfile --description 'If this option is given, the output will be wri… [See Man Page]'

