# hal-disable-polling
# Autogenerated from man page /usr/share/man/man1/hal-disable-polling.1.gz
# using Deroffing man parser
complete -c hal-disable-polling -l udi --description 'The UDI (Unique Device Identifier) of the device object.'
complete -c hal-disable-polling -l device --description 'The device file of the drive.'
complete -c hal-disable-polling -l enable-polling --description 'Enable polling instead of disabling it.'
complete -c hal-disable-polling -l help --description 'Print out usage.'
complete -c hal-disable-polling -l version --description 'Print the version.'

