# hal-is-caller-locked-out
# Autogenerated from man page /usr/share/man/man1/hal-is-caller-locked-out.1.gz
# using Deroffing man parser
complete -c hal-is-caller-locked-out -l udi --description 'The UDI (Unique Device Identifier) of the device object.'
complete -c hal-is-caller-locked-out -l interface --description 'The name of the interface to check for.'
complete -c hal-is-caller-locked-out -l caller --description 'The unique D-Bus name on the system bus of the caller.'
complete -c hal-is-caller-locked-out -l help --description 'Print out usage.'
complete -c hal-is-caller-locked-out -l version --description 'Print the version.'

