# hal-find-by-capability
# Autogenerated from man page /usr/share/man/man1/hal-find-by-capability.1.gz
# using Deroffing man parser
complete -c hal-find-by-capability -l capability --description 'The name of the capability.'
complete -c hal-find-by-capability -l verbose --description 'Verbose output.'
complete -c hal-find-by-capability -l help --description 'Print out usage.'
complete -c hal-find-by-capability -l version --description 'Print the version.'

