# hardening-check
# Autogenerated from man page /usr/share/man/man1/hardening-check.1.gz
# using Type1
complete -c hardening-check -l nopie -s p --description 'No not require that the checked binaries be bui… [See Man Page]'
complete -c hardening-check -l nostackprotector -s s --description 'No not require that the checked binaries be bui… [See Man Page]'
complete -c hardening-check -l nofortify -s f --description 'No not require that the checked binaries be bui… [See Man Page]'
complete -c hardening-check -l norelro -s r --description 'No not require that the checked binaries be bui… [See Man Page]'
complete -c hardening-check -l nobindnow -s b --description 'No not require that the checked binaries be bui… [See Man Page]'
complete -c hardening-check -l quiet -s q --description 'Only report failures.'
complete -c hardening-check -l verbose --description 'Report verbosely on failures.'
complete -c hardening-check -l report-functions --description 'After the report, display all external function… [See Man Page]'
complete -c hardening-check -l find-libc-functions --description 'Instead of the regular report, locate the libc … [See Man Page]'
complete -c hardening-check -l color --description 'Enable colorized status output.'
complete -c hardening-check -l lintian --description 'Switch reporting to lintian-check-parsable output.'
complete -c hardening-check -l debug --description 'Report some debugging during processing.'
complete -c hardening-check -l help -s h -s '?' --description 'Print a brief help message and exit.'

