# irunner
# Autogenerated from man page /usr/share/man/man1/irunner.1.gz
# using Deroffing man parser
complete -c irunner -s h -l help --description 'show this help message and exit.'
complete -c irunner -l ipython --description 'IPython interactive runner (default).'
complete -c irunner -l python --description 'Python interactive runner.'
complete -c irunner -l sage --description 'SAGE interactive runner.  EXAMPLE irunner.'

