# krb5-config
# Autogenerated from man page /usr/share/man/man1/krb5-config.1.gz
# using Deroffing man parser
complete -c krb5-config -l help --description 'print usage message.   This is the default.'
complete -c krb5-config -l all --description 'prints version, vendor, prefix and exec-prefix.'
complete -c krb5-config -l version --description 'prints the version of the installed Kerberos implementation.'
complete -c krb5-config -l vendor --description 'prints the vendor of the installed Kerberos implementation.'
complete -c krb5-config -l prefix --description 'prints the prefix with which Kerberos was built.'
complete -c krb5-config -l exec-prefix --description 'prints the exec-prefix with which Kerberos was built.'
complete -c krb5-config -l cflags --description 'prints the compiler flags with which Kerberos was built.'
complete -c krb5-config -l libs --description 'list compiler options required to link with libraries.'

