# libgcrypt-config
# Autogenerated from man page /usr/share/man/man1/libgcrypt-config.1.gz
# using Deroffing man parser
complete -c libgcrypt-config -l version --description 'Print the currently installed version of libgcr… [See Man Page]'
complete -c libgcrypt-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c libgcrypt-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c libgcrypt-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c libgcrypt-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

