# libmikmod-config
# Autogenerated from man page /usr/share/man/man1/libmikmod-config.1.gz
# using Deroffing man parser
complete -c libmikmod-config -l version --description 'Print the currently installed version of libmik… [See Man Page]'
complete -c libmikmod-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c libmikmod-config -l ldadd --description 'Print the extra linker flags that are necessary… [See Man Page]'
complete -c libmikmod-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c libmikmod-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c libmikmod-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

