# licensecheck
# Autogenerated from man page /usr/share/man/man1/licensecheck.1.gz
# using Type1
complete -c licensecheck -l verbose -l no-verbose --description 'Specify whether to output the text being proces… [See Man Page]'
complete -c licensecheck -s l -l lines --description 'Specify the number of lines of each file\'s head… [See Man Page]'
complete -c licensecheck -s i -l ignore --description 'When processing the list of files and directori… [See Man Page]'
complete -c licensecheck -s r -l recursive --description 'Specify that the contents of directories should… [See Man Page]'
complete -c licensecheck -s c -l check --description 'Specify a pattern against which filenames will … [See Man Page]'
complete -c licensecheck -l copyright --description 'Also display copyright text found within the file.'
complete -c licensecheck -s m -l machine --description 'Display the information in a machine readable way, i. e.'

