# lilyterm
# Autogenerated from man page /usr/share/man/man1/lilyterm.1.gz
# using Deroffing man parser
complete -c lilyterm -s '?' -s h -l help --description '.'
complete -c lilyterm -s v -l version --description '.'
complete -c lilyterm -s d -l directory --description '.'
complete -c lilyterm -s g -l geometry --description '.'
complete -c lilyterm -s l -o ls -l login --description '.'
complete -c lilyterm -s H -l hold --description '.'
complete -c lilyterm -s p -l profile --description '.'
complete -c lilyterm -s s -l separate --description '.'
complete -c lilyterm -s T -l title --description '.'
complete -c lilyterm -s t -l tab --description '.'
complete -c lilyterm -s u -l user_profile --description '.'
complete -c lilyterm -s e -s x -l execute --description '.'

