# live-snapshot
# Autogenerated from man page /usr/share/man/man1/live-snapshot.1.gz
# using Deroffing man parser
complete -c live-snapshot -s c -l cow --description 'specifies the input directory to be cloned in the image file.'
complete -c live-snapshot -s d -l device --description 'sets the device where the media which the snaps… [See Man Page]'
complete -c live-snapshot -s e -l exclude-list --description 'a file containing a list of filenames/paths tha… [See Man Page]'
complete -c live-snapshot -s o -l output --description 'the filename/label used for the output file/partition.'
complete -c live-snapshot -s r -l resync-string --description 'internally used on resyncs.'
complete -c live-snapshot -s f -l refresh --description 'try to do the same operation that should be don… [See Man Page]'
complete -c live-snapshot -s t -l type --description 'Type could be one of "cpio", "squashfs", "ext2"… [See Man Page]'
complete -c live-snapshot -s h -l help --description 'display help and exit.'
complete -c live-snapshot -s u -l usage --description 'show usage and exit.'
complete -c live-snapshot -s v -l version --description 'output version information and exit.'

