# lneato
# Autogenerated from man page /usr/share/man/man1/lneato.1.gz
# using Deroffing man parser
complete -c lneato -s V --description 'Prints the version.  SEE ALSO neato(1), lefty(1), dotty(1),.'

