# manpage-alert
# Autogenerated from man page /usr/share/man/man1/manpage-alert.1.gz
# using Deroffing man parser
complete -c manpage-alert -l help -s h --description 'Show a summary of options.'
complete -c manpage-alert -l version -s v --description 'Show version and copyright information.'

