# mdmflexiserver
# Autogenerated from man page /usr/share/man/man1/mdmflexiserver.1.gz
# using Type1
complete -c mdmflexiserver -s c -l command --description 'Send the specified protocol command to mdm.'
complete -c mdmflexiserver -s n -l xnest --description 'Xnest mode.'
complete -c mdmflexiserver -s l -l no-lock --description 'Do not lock current screen.'
complete -c mdmflexiserver -s d -l debug --description 'Debugging output.'

