# mid3iconv
# Autogenerated from man page /usr/share/man/man1/mid3iconv.1.gz
# using Deroffing man parser
complete -c mid3iconv -l debug -s d --description 'Print updated tags.'
complete -c mid3iconv -l dry-run -s p --description 'Do not actually modify files.'
complete -c mid3iconv -l encoding -s e --description 'Convert from this encoding.'
complete -c mid3iconv -l force-v1 --description 'Use an ID3v1 tag even if an ID3v2 tag is present.'
complete -c mid3iconv -l quiet -s q --description 'Only output errors.'
complete -c mid3iconv -l remove-v1 --description 'Remove any ID3v1 tag after processing the files… [See Man Page]'

