# mid3v2
# Autogenerated from man page /usr/share/man/man1/mid3v2.1.gz
# using Deroffing man parser
complete -c mid3v2 -s q -l quiet --description 'Be quiet: do not mention file operations that p… [See Man Page]'
complete -c mid3v2 -s v -l verbose --description 'Be verbose: state all operations performed.'
complete -c mid3v2 -s f -l list-frames --description 'Display all supported ID3v2. 3/2. 4 frames and their meanings.'
complete -c mid3v2 -s L -l list-genres --description 'List all ID3v1 numeric genres.'
complete -c mid3v2 -s l -l list --description 'List all tags in the files.'
complete -c mid3v2 -l list-raw --description 'List all tags in the files, in raw format.'
complete -c mid3v2 -s d -l delete-v2 --description 'Delete ID3v2 tags.'
complete -c mid3v2 -s s -l delete-v1 --description 'Delete ID3v1 tags.'
complete -c mid3v2 -s D -l delete-all --description 'Delete all ID3 tags.'
complete -c mid3v2 -l delete-frames --description 'Delete specific ID3v2 frames (or groups of fram… [See Man Page]'
complete -c mid3v2 -s C -l convert --description 'Convert ID3v1 tags to ID3v2 tags.'
complete -c mid3v2 -s a -l artist --description 'Set the artist information (TPE1).'
complete -c mid3v2 -s A -l album --description 'Set the album information (TALB).'
complete -c mid3v2 -s t -l song --description 'Set the title information (TIT2).'
complete -c mid3v2 -s c -l comment --description 'Set a comment (COMM).'
complete -c mid3v2 -s g -l genre --description 'Set the genre information (TCON).'
complete -c mid3v2 -s y -l year -l date --description 'Set the year/date information (TDRC).'
complete -c mid3v2 -l 'quiet.' --description '.'
complete -c mid3v2 -o Tnum/num -l track --description 'Set the track number (TRCK).'
complete -c mid3v2 -l TIT3 --description '.'

