# mk-build-deps
# Autogenerated from man page /usr/share/man/man1/mk-build-deps.1.gz
# using Type1
complete -c mk-build-deps -s i -l install --description 'Install the generated packages and its build-dependencies.'
complete -c mk-build-deps -s t -l tool --description 'When installing the generated package use the specified tool.'
complete -c mk-build-deps -s r -l remove --description 'Remove the package file after installing it.'
complete -c mk-build-deps -s a -l arch --description 'If the source package has architecture-specific… [See Man Page]'
complete -c mk-build-deps -s B -l build-dep --description 'Generate a package which only depends on the so… [See Man Page]'
complete -c mk-build-deps -s A -l build-indep --description 'Generate a package which only depends on the so… [See Man Page]'
complete -c mk-build-deps -s h -l help --description 'Show a summary of options.'
complete -c mk-build-deps -s v -l version --description 'Show version and copyright information.'

