# moggsplit
# Autogenerated from man page /usr/share/man/man1/moggsplit.1.gz
# using Deroffing man parser
complete -c moggsplit -l extension --description 'Use the supplied extension when generating new … [See Man Page]'
complete -c moggsplit -l pattern --description 'Use the supplied pattern when generating new files.'
complete -c moggsplit -l m3u --description 'Generate an m3u playlist along with the newly generated files.'

