# mongodump
# Autogenerated from man page /usr/share/man/man1/mongodump.1.gz
# using Type1
complete -c mongodump -l help --description 'show usage information.'
complete -c mongodump -s h -l host --description 'server to connect to (default HOST=localhost).'
complete -c mongodump -s d -l db --description 'database to use.'
complete -c mongodump -s c -l c --description 'collection to use.'
complete -c mongodump -s o -l out --description 'output file, if not specified, stdout is used.'

