# mongoexport
# Autogenerated from man page /usr/share/man/man1/mongoexport.1.gz
# using Type1
complete -c mongoexport -l help --description 'show usage information.'
complete -c mongoexport -s h -l host --description 'server to connect to (default HOST=localhost).'
complete -c mongoexport -s d -l db --description 'database to use.'
complete -c mongoexport -s c -l c --description 'collection to use.'
complete -c mongoexport -s q -l query --description 'query filter.'
complete -c mongoexport -s f -l fields --description 'comma-separated list of field names.'
complete -c mongoexport -l csv --description 'export to CSV instead of JSON.'
complete -c mongoexport -s o -l out --description 'output file, if not specified, stdout is used.'

