# mongostat
# Autogenerated from man page /usr/share/man/man1/mongostat.1.gz
# using Type1
complete -c mongostat -l help --description 'show usage information.'
complete -c mongostat -s h -l host --description 'mongo host to connect to (use "left,right" for pairs) \\".'
complete -c mongostat -l port --description '\\" port to connect to (default PORT=27017).'
complete -c mongostat -s d -l db --description 'db to use.'
complete -c mongostat -s c -l collection --description 'collection to use (some commands).'
complete -c mongostat -s u -l username --description 'specify user to log in as.'

