# mongosniff
# Autogenerated from man page /usr/share/man/man1/mongosniff.1.gz
# using Type1
complete -c mongosniff -l forward --description 'Forward all parsed request messages to mongod i… [See Man Page]'
complete -c mongosniff -l source --description 'Source of traffic to sniff, either a network in… [See Man Page]'
complete -c mongosniff -l help --description 'print a short help message.'

