# mongofiles
# Autogenerated from man page /usr/share/man/man1/mongofiles.1.gz
# using Type1
complete -c mongofiles -l help --description 'show usage information.'
complete -c mongofiles -s h -l host --description 'mongo host to which to connect.'
complete -c mongofiles -s d -l db --description 'database to use (default DB=test).'
complete -c mongofiles -s c -l collection --description 'collection to use.'
complete -c mongofiles -l command --description 'execute a command.'
complete -c mongofiles -l file --description 'filename for get or put.'

