# monop2
# Autogenerated from man page /usr/share/man/man1/monop2.1.gz
# using Deroffing man parser
complete -c monop2 -o r:assembly --description 'Specifies the assembly to use for looking up the type.'
complete -c monop2 -s a --description 'Renders all of the types in the specified assembly.'
complete -c monop2 -l search -s s -s k --description 'Searches through all known assemblies for types… [See Man Page]'
complete -c monop2 -l refs --description 'Prints a list of the referenced assemblies for an assembly.'
complete -c monop2 -l filter-obsolete -s f --description 'Do not show obsolete types and members.'
complete -c monop2 -l declared-only -s d --description 'Only show members declared in the type.'
complete -c monop2 -l private -s p --description 'Show private members.'
complete -c monop2 -l runtime-version --description 'Print runtime version.'

