# mpost
# Autogenerated from man page /usr/share/man/man1/mpost.1.gz
# using Deroffing man parser
complete -c mpost -l ini --description 'option is given, preloading does not happen.'
complete -c mpost -l dvitomp --description 'option is given,  acts as DVI-to-MPX converter only.'

