# mptopdf
# Autogenerated from man page /usr/share/man/man1/mptopdf.1.gz
# using Type1
complete -c mptopdf -l help --description 'Print a terse help message.'
complete -c mptopdf -l metafun --description 'Use the metafun pre-compiled format to process … [See Man Page]'
complete -c mptopdf -l rawmp --description 'Process the source file with  mpost (1) directl… [See Man Page]'

