# nc
# Autogenerated from man page /usr/share/man/man1/nc.traditional.1.gz
# using Deroffing man parser
complete -c nc -s c --description 'specify shell commands to exec after connect (u… [See Man Page]'
complete -c nc -s e --description 'specify filename to exec after connect (use with caution).'
complete -c nc -s g --description 'source-routing hop point[s], up to 8.'
complete -c nc -s G --description 'source-routing pointer: 4, 8, 12, .'
complete -c nc -s o --description 'hex dump of traffic.'

