# ncdu
# Autogenerated from man page /usr/share/man/man1/ncdu.1.gz
# using Deroffing man parser
complete -c ncdu -s h --description 'Print a small help message.'
complete -c ncdu -s q --description 'Quiet mode.'
complete -c ncdu -s r --description 'Read-only mode.'
complete -c ncdu -s v --description 'Print version.'
complete -c ncdu -s x --description 'Only count files and directories on the same fi… [See Man Page]'
complete -c ncdu -l exclude --description 'Exclude files that match PATTERN.'
complete -c ncdu -s X -l exclude-from --description 'Exclude files that match any pattern in FILE.'

