# netbeans
# Autogenerated from man page /usr/share/man/man1/netbeans.1.gz
# using Type1
complete -c netbeans -l help --description 'List available command line options.'
complete -c netbeans -l jdkhome --description 'Path to JDK home used to run IDE.'
complete -c netbeans -o 'J<jvm_option>' --description 'Pass <jvm_option> to JVM.'
complete -c netbeans -l cp:p --description 'Prepend <classpath> to classpath.'
complete -c netbeans -l cp:a --description 'Append <classpath> to classpath . LP  Core options:.'
complete -c netbeans -l laf --description 'Use given LookAndFeel class instead of the default.'
complete -c netbeans -l fontsize --description 'Set the base font size of the user interface, in points.'
complete -c netbeans -l locale --description 'Use specified locale.'
complete -c netbeans -l userdir --description 'Use specified directory to store user settings .'
complete -c netbeans -l reload --description 'Installs or reinstalls a module JAR file.'
complete -c netbeans -l open --description 'Open FILE.'

