# ntpdc
# Autogenerated from man page /usr/share/man/man1/ntpdc.1.gz
# using Deroffing man parser
complete -c ntpdc -s 4 --description 'Force DNS resolution of following host names on… [See Man Page]'
complete -c ntpdc -s 6 --description 'Force DNS resolution of following host names on… [See Man Page]'
complete -c ntpdc -s c --description 'The following argument is interpreted as an int… [See Man Page]'
complete -c ntpdc -s i --description 'Force ntpdc to operate in interactive mode.'
complete -c ntpdc -s l --description 'Obtain a list of peers which are known to the server(s).'
complete -c ntpdc -s n --description 'Output all host addresses in dotted-quad numeri… [See Man Page]'
complete -c ntpdc -s p --description 'Print a list of the peers known to the server a… [See Man Page]'
complete -c ntpdc -s s --description 'Print a list of the peers known to the server a… [See Man Page]'

