# ntpq
# Autogenerated from man page /usr/share/man/man1/ntpq.1.gz
# using Deroffing man parser
complete -c ntpq -s 4 --description 'Force DNS resolution of following host names on… [See Man Page]'
complete -c ntpq -s 6 --description 'Force DNS resolution of following host names on… [See Man Page]'
complete -c ntpq -s c --description 'The following argument is interpreted as an int… [See Man Page]'
complete -c ntpq -s i --description 'Force ntpq to operate in interactive mode.'
complete -c ntpq -s n --description 'Output all host addresses in dotted-quad numeri… [See Man Page]'
complete -c ntpq -s p --description 'Print a list of the peers known to the server a… [See Man Page]'

