# otangle
# Autogenerated from man page /usr/share/man/man1/otangle.1.gz
# using Type1
complete -c otangle -l help --description 'Print help message and exit.'
complete -c otangle -l length --description 'Compare only the first  number characters of id… [See Man Page]'
complete -c otangle -l loose --description 'When checking for collisions between identifier… [See Man Page]'
complete -c otangle -l lowercase --description 'Convert all identifiers to lowercase.'
complete -c otangle -l mixedcase --description 'Retain the case of identifiers.   This is the default.'
complete -c otangle -l strict --description 'When checking for collisions between identifier… [See Man Page]'
complete -c otangle -l underline --description 'Retain underlines (also known as underscores) in identifiers.'
complete -c otangle -l uppercase --description 'Convert all identifiers to uppercase.'

