# pmap
# Autogenerated from man page /usr/share/man/man1/pmap.1.gz
# using Deroffing man parser
complete -c pmap -s x -l extended --description 'Show the extended format.'
complete -c pmap -s d -l device --description 'Show the device format.'
complete -c pmap -s q -l quiet --description 'Do not display some header or footer lines.'
complete -c pmap -s A -l range --description 'Limit results to the given range to  low and  h… [See Man Page]'
complete -c pmap -s h -l help --description 'Display help text and exit.'
complete -c pmap -s V -l version --description 'Display version information and exit.  EXIT STATUS 0 Success.'

