# quilt
# Autogenerated from man page /usr/share/man/man1/quilt.1.gz
# using Deroffing man parser
complete -c quilt -l trace --description '.'
complete -c quilt -l quiltrc --description '.'
complete -c quilt -l version --description '.'

