# ranger
# Autogenerated from man page /usr/share/man/man1/ranger.1.gz
# using Type1
complete -c ranger -s d -l debug --description 'Activate the debug mode: Whenever an error occu… [See Man Page]'
complete -c ranger -s c -l clean --description 'Activate the clean mode:  ranger will not acces… [See Man Page]'
complete -c ranger -l choosefile --description 'Allows you to pick a file with ranger.'
complete -c ranger -l choosefiles --description 'Allows you to pick multiple files with ranger.'
complete -c ranger -l choosedir --description 'Allows you to pick a directory with ranger.'
complete -c ranger -l selectfile --description 'Open ranger with targetfile selected.'
complete -c ranger -l copy-config --description 'Create copies of the default configuration file… [See Man Page]'
complete -c ranger -l list-unused-keys --description 'List common keys which are not bound to any act… [See Man Page]'
complete -c ranger -l list-tagged-files --description 'List all files which are tagged with the given tag.'
complete -c ranger -l fail-unless-cd --description 'Return the exit code 1 if ranger is used to run… [See Man Page]'
complete -c ranger -s m -l mode --description 'When a filename is supplied, run it in mode n.'
complete -c ranger -s f -l flags --description 'When a filename is supplied, run it with the gi… [See Man Page]'
complete -c ranger -l cmd --description 'Execute the command after the configuration has been read.'
complete -c ranger -l version --description 'Print the version and exit.'

