# rapt-file
# Autogenerated from man page /usr/share/man/man1/rapt-file.1.gz
# using Type1
complete -c rapt-file -s a -l architecture --description 'Sets architecture to architecture.'
complete -c rapt-file -s l -l package-only --description 'Only display package name; do not display file names.'
complete -c rapt-file -s v -l verbose --description 'Run rapt-file in verbose mode.'

