# rc-alert
# Autogenerated from man page /usr/share/man/man1/rc-alert.1.gz
# using Deroffing man parser
complete -c rc-alert -l cache --description 'Force the creation of the ~/. devscripts_cache cache directory.'
complete -c rc-alert -l help -s h --description 'Show a summary of options.'
complete -c rc-alert -l version -s v --description 'Show version and copyright information.'
complete -c rc-alert -l include-tags -s f --description 'A list of tags which the bug must have, in the … [See Man Page]'
complete -c rc-alert -l include-tag-op -s t --description 'If set to and, a bug must have all of the tags … [See Man Page]'
complete -c rc-alert -l exclude-tags --description 'A list of tags which the bug must not have, in … [See Man Page]'
complete -c rc-alert -l exclude-tag-op --description 'If set to and, a bug must have none of the tags… [See Man Page]'
complete -c rc-alert -l include-dists -s d --description 'A list of distributions which the bug must appl… [See Man Page]'
complete -c rc-alert -l include-dist-op -s o --description 'If set to and, a bug must apply to all of the s… [See Man Page]'
complete -c rc-alert -l exclude-dists --description 'A list of distributions to which the bug must n… [See Man Page]'
complete -c rc-alert -l exclude-dist-op --description 'If set to and, a bug must apply to all of the s… [See Man Page]'
complete -c rc-alert -l debtags --description 'Match packages based on the listed tags.'
complete -c rc-alert -l debtags-database --description 'Use a non-standard debtags database.'
complete -c rc-alert -l popcon --description 'Sort bugs by the popcon rank of the package the bug belongs to.'
complete -c rc-alert -l pc-vote --description 'By default, packages are sorted according to th… [See Man Page]'
complete -c rc-alert -l 'include-tags.' --description '.'
complete -c rc-alert -l 'exclude-tags.' --description 'matches.'
complete -c rc-alert -l 'include-dists.' --description '.'
complete -c rc-alert -l pc-local --description 'Instead of requesting remote data the informati… [See Man Page]'

