# realpath
# Autogenerated from man page /usr/share/man/man1/realpath.1.gz
# using Deroffing man parser
complete -c realpath -s s -l strip --description 'Only strip  .  and  .'
complete -c realpath -s z -l zero --description 'Separate output filenames with the null charact… [See Man Page]'
complete -c realpath -s h -l help --description 'Print short usage information. \\".'

