# regexp-assemble
# Autogenerated from man page /usr/share/man/man1/regexp-assemble.1p.gz
# using Type1
complete -c regexp-assemble -s a --description 'look Ahead.  Insert \\f(CW\\*(C`(?=.'
complete -c regexp-assemble -s b --description 'Blank.  Ignore blank lines.'
complete -c regexp-assemble -s c --description 'Comment.  Basic comment filtering.'
complete -c regexp-assemble -s d --description 'Debug.  Turns on debugging output.'
complete -c regexp-assemble -s i --description 'Indent.'
complete -c regexp-assemble -s n --description 'No newline.  Do not print a newline after the pattern.'
complete -c regexp-assemble -s p --description 'Print.  Print the pattern.'
complete -c regexp-assemble -s r --description 'Reduce.'
complete -c regexp-assemble -s s --description 'Statistics.  Print some statistics about the assembled pattern.'
complete -c regexp-assemble -s S --description 'Statistics only.'
complete -c regexp-assemble -s t --description 'Test.'
complete -c regexp-assemble -s T --description 'Time.'
complete -c regexp-assemble -s u --description 'Unique.  Carp if duplicate patterns are found.'
complete -c regexp-assemble -s U --description 'Unroll.'
complete -c regexp-assemble -s v --description 'Version.  Print the version of the regexp-assemble script.'

