# rmadison
# Autogenerated from man page /usr/share/man/man1/rmadison.1.gz
# using Type1
complete -c rmadison -s a -l architecture --description 'only show info for \\s-1ARCH\\s0(s).'
complete -c rmadison -s b -l binary-type --description 'only show info for binary \\s-1TYPE\\s0.'
complete -c rmadison -s c -l component --description 'only show info for \\s-1COMPONENT\\s0(s).'
complete -c rmadison -s g -l greaterorequal --description 'show buildd \'dep-wait pkg >= {highest version}\' info.'
complete -c rmadison -s G -l greaterthan --description 'show buildd \'dep-wait pkg >> {highest version}\' info.'
complete -c rmadison -s h -l help --description 'show this help and exit.'
complete -c rmadison -s s -l suite --description 'only show info for this suite.'
complete -c rmadison -s S -l source-and-binary --description 'show info for the binary children of source pkgs.'
complete -c rmadison -s t -l time --description 'show projectb snapshot and reload time (not sup… [See Man Page]'
complete -c rmadison -s u -l url --description 'use \\s-1URL\\s0 for the query.'
complete -c rmadison -l version --description 'show version and exit.'

