# rstconv
# Autogenerated from man page /usr/share/man/man1/rstconv.1.gz
# using Deroffing man parser
complete -c rstconv -s f --description 'Specify the output file format.'
complete -c rstconv -s h -l 'help)' --description 'outputs a short help message.'
complete -c rstconv -s i --description 'Specifies the input file name.'
complete -c rstconv -s o --description 'to specify the output file name.'

