# rstconv-2
# Autogenerated from man page /usr/share/man/man1/rstconv-2.6.0.1.gz
# using Deroffing man parser
complete -c rstconv-2 -s f --description 'Specify the output file format.'
complete -c rstconv-2 -s h -l 'help)' --description 'outputs a short help message.'
complete -c rstconv-2 -s i --description 'Specifies the input file name.'
complete -c rstconv-2 -s o --description 'to specify the output file name.'

