# ruby1
# Autogenerated from man page /usr/share/man/man1/ruby1.9.1.1.gz
# using Darwin man parser
complete -c ruby1 -s X --description 'Causes Ruby to switch to the directory.  Pp.'
complete -c ruby1 -s E --description '.'
complete -c ruby1 -l encoding --description 'Specifies the default value(s) for external enc… [See Man Page]'
complete -c ruby1 -s U --description 'Sets the default value for internal encodings ( Li "Encoding.'
complete -c ruby1 -s W --description 'Turns on verbose mode at the specified level, w… [See Man Page]'
complete -c ruby1 -l disable- --description '.'
complete -c ruby1 -l enable- --description 'Disables (or enables) the specified FEATURE Ns \\&.'
complete -c ruby1 -l disable-gems --description '.'
complete -c ruby1 -l enable-gems --description 'Disables (or enables) RubyGems libraries.'
complete -c ruby1 -l disable-rubyopt --description '.'
complete -c ruby1 -l enable-rubyopt --description 'Ignores (or considers) the RUBYOPT environment variable.'
complete -c ruby1 -l disable-all --description '.'
complete -c ruby1 -l enable-all --description 'Disables (or enables) all features.  Pp El Pp.'
complete -c ruby1 -l dump --description 'DO NOT USE.  Pp Prints the specified target.'

