# sctp_darn
# Autogenerated from man page /usr/share/man/man1/sctp_darn.1.gz
# using Deroffing man parser
complete -c sctp_darn -s H -l local --description 'specify one of the local addresses.'
complete -c sctp_darn -s P -l local-port --description 'specify the port number for local addresses.'
complete -c sctp_darn -s h -l remote --description 'specify the peer address.'
complete -c sctp_darn -s p -l remote-port --description 'specify the port number for the peer address.'
complete -c sctp_darn -s l -l listen --description 'print messages received from the peer.'
complete -c sctp_darn -s s -l send --description 'send messages to the peer.'
complete -c sctp_darn -s B -l bindx-add --description 'add the specified address(es) as additional bin… [See Man Page]'
complete -c sctp_darn -s b -l bindx-rem --description 'remove the specified address(es) from the bind … [See Man Page]'
complete -c sctp_darn -s I --description 'use the interactive mode.'
complete -c sctp_darn -s i --description 'setup the specified number of endpoints by usin… [See Man Page]'
complete -c sctp_darn -s m --description 'specify the sockopt sndbuf/rcvbuf size.'
complete -c sctp_darn -s n --description 'set the socket(s) to be in the non-blocking mode.'
complete -c sctp_darn -l use-poll --description 'use system call poll() for polling among the nu… [See Man Page]'
complete -c sctp_darn -s t --description 'use SOCK_STREAM tcp-style sockets.'
complete -c sctp_darn -s z --description 'specify the message size to be sent.'
complete -c sctp_darn -l interface --description 'select interface for sin6_scope_id.'

