# seahorse-daemon
# Autogenerated from man page /usr/share/man/man1/seahorse-daemon.1.gz
# using Type1
complete -c seahorse-daemon -s '?' -l help --description 'Show summary of all options and exit.'
complete -c seahorse-daemon -l usage --description 'Display brief usage message and exit. \\" End List  .'

