# sfddiff
# Autogenerated from man page /usr/share/man/man1/sfddiff.1.gz
# using Deroffing man parser
complete -c sfddiff -l help --description 'Provide a description with a list of the available options.'
complete -c sfddiff -l ignorehints --description 'Suppress the reporting of hint/instruction differences.'
complete -c sfddiff -l ignoregpos --description 'Suppress the reporting of kerning (and other `g… [See Man Page]'
complete -c sfddiff -l ignoregsub --description 'Suppress the reporting of ligature (and other `… [See Man Page]'
complete -c sfddiff -l ignorenames --description 'Suppress the reporting of name string differences.'
complete -c sfddiff -l ignorebitmaps --description 'Suppress the reporting of bitmap differences.'
complete -c sfddiff -l exact --description 'Require outlines to match exactly.'
complete -c sfddiff -l warn --description 'Warn if the outlines/references are slightly different.'
complete -c sfddiff -l merge --description 'Store a merged version of the two fonts into th… [See Man Page]'
complete -c sfddiff -l usage --description 'Display the usage description.'
complete -c sfddiff -l version --description 'Display the current version.  SEE ALSO.'
complete -c sfddiff -o man --description 'macros by R. P. C.  Rodgers (rodgers@nlm. nih.'

