# sgmlnorm
# Autogenerated from man page /usr/share/man/man1/sgmlnorm.1.gz
# using Type1
complete -c sgmlnorm -o bbctf --description 'Use the BCTF name bctf for output.'
complete -c sgmlnorm -o cfile --description 'Use the catalog entry file file.'
complete -c sgmlnorm -s C --description 'The filename.'
complete -c sgmlnorm -s d --description 'Output a document type declaration with the sam… [See Man Page]'
complete -c sgmlnorm -o Ddirectory --description 'Search directory for files specified in system identifiers.'
complete -c sgmlnorm -s e --description 'Describe open entities in error messages.'
complete -c sgmlnorm -o iname --description 'Pretend that <!ENTITY % name "INCLUDE"> occurs … [See Man Page]'
complete -c sgmlnorm -s m --description 'Output any marked sections that were in the inp… [See Man Page]'
complete -c sgmlnorm -s n --description 'Output any comments that were in the input document instance.'
complete -c sgmlnorm -s r --description 'Raw output.'
complete -c sgmlnorm -s v --description 'Print the version number.'

