# sgml2xml
# Autogenerated from man page /usr/share/man/man1/sgml2xml.1.gz
# using Type1
complete -c sgml2xml -o bencoding --description 'Use encoding for output.   The default is UTF-8.'
complete -c sgml2xml -o ccatalog --description 'Use the catalog entry file file.'
complete -c sgml2xml -s C --description 'The filename.'
complete -c sgml2xml -o Ddirectory --description 'Search directory for files specified in system identifiers.'
complete -c sgml2xml -s e --description 'Describe open entities in error messages.'
complete -c sgml2xml -o ffile --description 'Redirect errors to file.'
complete -c sgml2xml -o iname --description 'Pretend that <!ENTITY % name "INCLUDE"> occurs … [See Man Page]'
complete -c sgml2xml -s v --description 'Print the version number.'
complete -c sgml2xml -o wtype --description 'Control warnings and errors according to type.'
complete -c sgml2xml -o xxml-output-option --description 'Control the XML output, according to the value … [See Man Page]'

