# spam
# Autogenerated from man page /usr/share/man/man1/spam.1.gz
# using Deroffing man parser
complete -c spam -s c --description 'Use the catalog entry file R file .'
complete -c spam -s D --description 'Search  directory for files specified in system identifiers.'
complete -c spam -s e --description 'Describe open entities in error messages.'
complete -c spam -s f --description 'Redirect errors to R file .'
complete -c spam -s h --description 'Hoist omitted tags out from the start of internal entities.'
complete -c spam -s i --description 'Pretend that . RS P  <!ENTITY% name \\(tsINCLUDE\\(ts> .'
complete -c spam -s l --description 'Prefer lower-case.'
complete -c spam -s m --description 'Change the markup in the output according to th… [See Man Page]'
complete -c spam -s o --description 'Output the general entity  name instead of the document entity.'
complete -c spam -s p --description 'Output the part of the document entity containi… [See Man Page]'
complete -c spam -s r --description 'Don\'t perform any conversion on RSs and REs whe… [See Man Page]'
complete -c spam -s v --description 'Print the version number.'
complete -c spam -s w --description 'Control warnings and errors according to R type .'
complete -c spam -s x --description 'opsion can be used so expand ensisy references.'
complete -c spam -o momissag --description 'or.'

