# spent
# Autogenerated from man page /usr/share/man/man1/spent.1.gz
# using Deroffing man parser
complete -c spent -s b --description 'Use the BCTF with name  bctf for output.'
complete -c spent -s r --description 'Don\'t perform any conversion on RSs and REs whe… [See Man Page]'
complete -c spent -s v --description 'Print the version number.  AUTHOR.'

