# synergys
# Autogenerated from man page /usr/share/man/man1/synergys.1.gz
# using Type1
complete -c synergys -s a -l address --description 'listen for clients on the given address.'
complete -c synergys -s c -l config --description 'use the named configuration file instead.'
complete -c synergys -s d -l debug --description 'filter out log messages with priority below  level.'
complete -c synergys -l display --description 'connect to the X server at display.'
complete -c synergys -l daemon --description 'run the server as a daemon.'
complete -c synergys -s f -l no-daemon --description 'run the server in the foreground.'
complete -c synergys -s n -l name --description 'use screen-name instead of  the hostname to ide… [See Man Page]'
complete -c synergys -l restart --description 'restart the server automatically if it fails.'
complete -c synergys -s 1 -l no-restart --description 'do not try to restart the server if it fails for some  reason.'
complete -c synergys -s h -l help --description 'display help and exit.'

