# tagpending
# Autogenerated from man page /usr/share/man/man1/tagpending.1.gz
# using Type1
complete -c tagpending -s n -l noact --description 'Check whether any bugs require tagging, but do … [See Man Page]'
complete -c tagpending -s s -l silent --description 'Do not output any messages.'
complete -c tagpending -s v -l verbose --description 'List each bug checked and tagged in turn.'
complete -c tagpending -s f -l force --description 'Do not query the \\s-1BTS\\s0, but (re)tag all bu… [See Man Page]'
complete -c tagpending -l comments --description 'Include the changelog header line and the entri… [See Man Page]'
complete -c tagpending -l no-comments --description 'Do not include changelog entries in the generated mail.'
complete -c tagpending -s c -l confirm --description 'Tag bugs as both confirmed and pending.'
complete -c tagpending -s t -l to --description 'Parse changelogs for all versions strictly grea… [See Man Page]'
complete -c tagpending -s i -l interactive --description 'Display the message which would be sent to the … [See Man Page]'

