# texworks
# Autogenerated from man page /usr/share/man/man1/texworks.1.gz
# using Deroffing man parser
complete -c texworks -l help -s '?' --description 'Display a short overview over all command line options.'
complete -c texworks -l position -s p --description 'Open the next specified file at the given posit… [See Man Page]'
complete -c texworks -l version -s v --description 'Display version information.'

