# typer
# Autogenerated from man page /usr/share/man/man1/typer.1.gz
# using Deroffing man parser
complete -c typer -s r --description 'Searches directories recursively for . erl files below them.'
complete -c typer -l show --description 'Prints type specifications for all functions on… [See Man Page]'
complete -c typer -l show-exported --description 'Same as --show, but prints specifications for e… [See Man Page]'
complete -c typer -l annotate --description 'Annotates the specified files with type specifications.'
complete -c typer -l annotate-inc-files --description 'Same as --annotate but annotates all -include()… [See Man Page]'
complete -c typer -l comments --description 'Prints type information using Edoc comments, no… [See Man Page]'
complete -c typer -l plt --description 'Uses the specified Dialyzer PLT file rather tha… [See Man Page]'
complete -c typer -s T --description 'The file file already contains type specificati… [See Man Page]'
complete -c typer -o Dname -o Dname --description 'Passes the defined name to TypEr.'
complete -c typer -s I --description 'Passes the include_dir to TypEr.'
complete -c typer -l version -o 'v)' --description 'Prints the TypEr version and exits.'
complete -c typer -l help -o 'h)' --description 'Prints help message and exits.'

