# typefortune
# Autogenerated from man page /usr/share/man/man1/typefortune.1.gz
# using Deroffing man parser
complete -c typefortune -s d --description 'use D: (drill) instead of S: (speed).'
complete -c typefortune -s s --description 'run fortune -s.'
complete -c typefortune -s l --description 'run fortune -l.'
complete -c typefortune -s n --description 'practice <count> fortunes (default=1).'
complete -c typefortune -s o --description 'pass options to gtypist EXAMPLE.'

