# udisks-glue
# Autogenerated from man page /usr/share/man/man1/udisks-glue.1.gz
# using Deroffing man parser
complete -c udisks-glue -o c/--config --description 'Use config-file as the configuration file.'
complete -c udisks-glue -o f/--foreground --description 'Remain in foreground (don\'t daemonize).'
complete -c udisks-glue -o h/--help --description 'Display usage information and exit.'
complete -c udisks-glue -o p/--pidfile --description 'Use pidfile file as the pidfile.'
complete -c udisks-glue -o s/--session --description 'Enable ConsoleKit session support FILES A confi… [See Man Page]'

