# unify
# Autogenerated from man page /usr/share/man/man1/unify.1.gz
# using Deroffing man parser
complete -c unify -s c -l context-diffs --description 'force output to context diffs.'
complete -c unify -s e -l echo-comments --description 'echo comments to standard error.'
complete -c unify -s o -l old-diffs --description 'output old-style diffs, no matter what.'
complete -c unify -s p -l patch-format --description 'generate patch format.'
complete -c unify -s P --description 'same as -p.'
complete -c unify -s s -l strip-comments --description 'strip comment lines.'
complete -c unify -s u -l unidiffs --description 'force output to unidiffs.'
complete -c unify -s U --description 'same as -p and -u.'
complete -c unify -l use-equals --description 'replace spaces by equal signs in unidiffs.'
complete -c unify -l help --description 'display this help then exit.'
complete -c unify -l version --description 'display program version then exit.'

