# unlzma
# Autogenerated from man page /usr/share/man/man1/unlzma.1.gz
# using Deroffing man parser
complete -c unlzma -s c -l stdout -l to-stdout --description 'The output is written to the standard output.'
complete -c unlzma -s d -l decompress -l uncompress --description 'Force decompression regardless of the invocation name.'
complete -c unlzma -s f -l force --description 'Force compression or decompression even if sour… [See Man Page]'
complete -c unlzma -s h -l help --description 'Show a summary of supported options and quit.'
complete -c unlzma -s k -l keep --description 'Do not delete the input files after compression… [See Man Page]'
complete -c unlzma -s L -l license --description 'Show licensing information of  lzma .'
complete -c unlzma -s q -l quiet --description 'Suppress all warnings.'
complete -c unlzma -s S -l suffix --description 'Use  . suf instead of the default  . lzma .'
complete -c unlzma -s t -l test --description 'Check the integrity of the compressed file(s).'
complete -c unlzma -s v -l verbose --description 'Show the filename and percentage reduction of e… [See Man Page]'
complete -c unlzma -s V -l version --description 'Show the version number of  lzma .'
complete -c unlzma -s z -l compress --description 'Force compression regardless of the invocation name.'
complete -c unlzma -s 1 -s 9 --description 'Set the compression ratio.'
complete -c unlzma -l fast --description 'Alias to  -1 .'
complete -c unlzma -o 'cd.' --description '.'
complete -c unlzma -l best --description 'Alias to.'

