# uptime
# Autogenerated from man page /usr/share/man/man1/uptime.1.gz
# using Deroffing man parser
complete -c uptime -s h -l help --description 'display this help text.'
complete -c uptime -s V -l version --description 'display version information and exit FILES.'

