# uupdate
# Autogenerated from man page /usr/share/man/man1/uupdate.1.gz
# using Deroffing man parser
complete -c uupdate -l upstream-version -s v --description 'Specify the version number of the upstream package explicitly.'
complete -c uupdate -l rootcmd -s r --description 'Specify the command to be used to become root t… [See Man Page]'
complete -c uupdate -l pristine -s u --description 'Treat the source as pristine upstream source an… [See Man Page]'
complete -c uupdate -l no-pristine --description 'Do not attempt to make a <package>_<version>. orig. tar.'
complete -c uupdate -l symlink -s s --description 'Simply create a symlink when moving a new upstream . tar.'
complete -c uupdate -l no-symlink --description 'Copy the upstream . tar.'
complete -c uupdate -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c uupdate -l help -s h --description 'Display a help message and exit successfully.'
complete -c uupdate -l version --description 'Display version and copyright information and e… [See Man Page]'

