# valgrind-listener
# Autogenerated from man page /usr/share/man/man1/valgrind-listener.1.gz
# using Deroffing man parser
complete -c valgrind-listener -s h -l help --description 'Show the help message.'
complete -c valgrind-listener -s e -l exit-at-zero --description 'Causes the listener to exit when the number of … [See Man Page]'
complete -c valgrind-listener -l log-socket --description 'option).'

