# visgrep
# Autogenerated from man page /usr/share/man/man1/visgrep.1.gz
# using Deroffing man parser
complete -c visgrep -s h --description 'Show summary of options.'
complete -c visgrep -s x --description 'Set x offset for detection matching.'
complete -c visgrep -s y --description 'Set y offset for detection matching.'
complete -c visgrep -s X --description 'Start scanning at X.'
complete -c visgrep -s Y --description 'Start scanning at Y.'
complete -c visgrep -s t --description 'Set tolerance for \'fuzzy\' matches, higher numbe… [See Man Page]'

