# wdiff
# Autogenerated from man page /usr/share/man/man1/wdiff.1.gz
# using Deroffing man parser
complete -c wdiff -s C -l copyright --description 'display copyright then exit.'
complete -c wdiff -s 1 -l no-deleted --description 'inhibit output of deleted words.'
complete -c wdiff -s 2 -l no-inserted --description 'inhibit output of inserted words.'
complete -c wdiff -s 3 -l no-common --description 'inhibit output of common words.'
complete -c wdiff -s a -l auto-pager --description 'automatically calls a pager.'
complete -c wdiff -s d -l diff-input --description 'use single unified diff as input.'
complete -c wdiff -s h -l help --description 'display this help then exit.'
complete -c wdiff -s i -l ignore-case --description 'fold character case while comparing.'
complete -c wdiff -s l -l less-mode --description 'variation of printer mode for "less".'
complete -c wdiff -s n -l avoid-wraps --description 'do not extend fields through newlines.'
complete -c wdiff -s p -l printer --description 'overstrike as for printers.'
complete -c wdiff -s s -l statistics --description 'say how many words deleted, inserted etc.'
complete -c wdiff -s t -l terminal --description 'use termcap as for terminal displays.'
complete -c wdiff -s v -l version --description 'display program version then exit.'
complete -c wdiff -s w -l start-delete --description 'string to mark beginning of delete region.'
complete -c wdiff -s x -l end-delete --description 'string to mark end of delete region.'
complete -c wdiff -s y -l start-insert --description 'string to mark beginning of insert region.'
complete -c wdiff -s z -l end-insert --description 'string to mark end of insert region COMPATIBILI… [See Man Page]'
complete -c wdiff -s K -l no-init-term --description 'Now synonymous to --terminal, which never initi… [See Man Page]'

