# wdiff2
# Autogenerated from man page /usr/share/man/man1/wdiff2.1.gz
# using Deroffing man parser
complete -c wdiff2 -s C -l copyright --description 'display copyright then exit.'
complete -c wdiff2 -s 1 -l no-deleted --description 'inhibit output of deleted words.'
complete -c wdiff2 -s 2 -l no-inserted --description 'inhibit output of inserted words.'
complete -c wdiff2 -s 3 -l no-common --description 'inhibit output of common words.'
complete -c wdiff2 -s a -l auto-pager --description 'automatically calls a pager.'
complete -c wdiff2 -s h -l help --description 'display this help then exit.'
complete -c wdiff2 -s i -l ignore-case --description 'fold character case while comparing.'
complete -c wdiff2 -s l -l less-mode --description 'variation of printer mode for "less".'
complete -c wdiff2 -s n -l avoid-wraps --description 'do not extend fields through newlines.'
complete -c wdiff2 -s p -l printer --description 'overstrike as for printers.'
complete -c wdiff2 -s q -l quiet --description 'inhibit the `mdiff\' call message.'
complete -c wdiff2 -s s -l statistics --description 'say how many words deleted, inserted etc.'
complete -c wdiff2 -s t -l terminal --description 'use termcap as for terminal displays.'
complete -c wdiff2 -s v -l version --description 'display program version then exit.'
complete -c wdiff2 -s w -l start-delete --description 'string to mark beginning of delete region.'
complete -c wdiff2 -s x -l end-delete --description 'string to mark end of delete region.'
complete -c wdiff2 -s y -l start-insert --description 'string to mark beginning of insert region.'
complete -c wdiff2 -s z -l end-insert --description 'string to mark end of insert region.'

