# what-patch
# Autogenerated from man page /usr/share/man/man1/what-patch.1.gz
# using Deroffing man parser
complete -c what-patch -s h -l help --description 'Display a help message and exit.'
complete -c what-patch -s v --description 'Enable verbose mode.'

