# wicd-gtk
# Autogenerated from man page /usr/share/man/man1/wicd-gtk.1.gz
# using Deroffing man parser
complete -c wicd-gtk -s t -l tray --description 'Run the wicd tray icon only.'
complete -c wicd-gtk -s n -l no-tray --description 'Run wicd without the tray icon.'
complete -c wicd-gtk -s h -l help --description 'Print this help information.'
complete -c wicd-gtk -s a -l no-animate --description 'Run the tray without network traffic tray animations.'

