# wicd-client
# Autogenerated from man page /usr/share/man/man1/wicd-client.1.gz
# using Deroffing man parser
complete -c wicd-client -s t -l tray --description 'Run the wicd tray icon only.'
complete -c wicd-client -s n -l no-tray --description 'Run wicd without the tray icon.'
complete -c wicd-client -s h -l help --description 'Print this help information.'
complete -c wicd-client -s a -l no-animate --description 'Run the tray without network traffic tray animations.'

