# winetricks
# Autogenerated from man page /usr/share/man/man1/winetricks.1.gz
# using Deroffing man parser
complete -c winetricks -l force --description 'Don\'t check whether packages were already installed.'
complete -c winetricks -l gui --description 'Show gui diagnostics even when driven by commandline.'
complete -c winetricks -s k -l keep_isos --description 'Cache isos (allows later installation without disc).'
complete -c winetricks -l no-clean --description 'Don\'t delete temp directories (useful during debugging).'
complete -c winetricks -l no-isolate --description 'Don\'t install each app or game in its own bottle.'
complete -c winetricks -s q -l unattended --description 'Don\'t ask any questions, just install automatically.'
complete -c winetricks -s r -l ddrescue --description 'Retry hard when caching scratched discs.'
complete -c winetricks -l showbroken --description 'Even show verbs that are currently broken in wine.'
complete -c winetricks -s v -l verbose --description 'Echo all commands as they are executed.'
complete -c winetricks -s h -l help --description 'Display this message and exit.'
complete -c winetricks -s V -l version --description 'Display version and exit.'

