# wnpp-alert
# Autogenerated from man page /usr/share/man/man1/wnpp-alert.1.gz
# using Deroffing man parser
complete -c wnpp-alert -l diff -s d --description 'If the ~/.'
complete -c wnpp-alert -l help -s h --description 'Show a summary of options.'
complete -c wnpp-alert -l version -s v --description 'Show version and copyright information.  SEE ALSO http://www.'

