# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
# using Deroffing man parser
complete -c x-window-manager -s v -l version --description 'Print version information to standard output, then exit.'
complete -c x-window-manager -s h -l help --description 'Print help information, then exit.'
complete -c x-window-manager -s c -l config --description 'Use an alternate configuration file instead of … [See Man Page]'
complete -c x-window-manager -s k -l check --description 'Check configuration file syntax.'

