# xbsh
# Autogenerated from man page /usr/share/man/man1/xbsh.1.gz
# using Deroffing man parser
complete -c xbsh -o classpath --description 'option which sets the value of the CLASSPATH en… [See Man Page]'

