# xgpsspeed
# Autogenerated from man page /usr/share/man/man1/xgpsspeed.1.gz
# using Deroffing man parser
complete -c xgpsspeed -s h --description 'option causes each client to emit a summary of … [See Man Page]'
complete -c xgpsspeed -s V --description 'option causes each client to dump the package version and exit.'
complete -c xgpsspeed -s l --description 'option, when present, sets the format of latitu… [See Man Page]'
complete -c xgpsspeed -s u --description 'option.'
complete -c xgpsspeed -s D --description 'option, when present, sets a debug level; it is… [See Man Page]'
complete -c xgpsspeed -s s --description 'option prevents cgps from displaying the data c… [See Man Page]'
complete -c xgpsspeed -s m --description 'option will display your magnetic heading (as o… [See Man Page]'
complete -c xgpsspeed -s i --description 'and defaulting to 5 seconds.'
complete -c xgpsspeed -s d --description 'option tells gpxlogger to run as a daemon in background.'
complete -c xgpsspeed -s f --description 'option, which directs output to a specified logfile.'
complete -c xgpsspeed -o 'l.' --description '.'
complete -c xgpsspeed -s e --description 'one of the colon-terminated method names from the.'

