# xvfb-run
# Autogenerated from man page /usr/share/man/man1/xvfb-run.1.gz
# using Deroffing man parser
complete -c xvfb-run -s a -l auto-servernum --description 'Try to get a free server number, starting at 99… [See Man Page]'
complete -c xvfb-run -s e -l error-file --description 'Store output from  xauth and  Xvfb in R file .'
complete -c xvfb-run -s f -l auth-file --description 'Store X authentication data in R file .'
complete -c xvfb-run -s h -l help --description 'Display a usage message and exit.'
complete -c xvfb-run -s n -l server-num --description 'Use  servernumber as the server number (but see… [See Man Page]'
complete -c xvfb-run -s l -l listen-tcp --description 'Enable TCP port listening in the X server.'
complete -c xvfb-run -s p -l xauth-protocol --description 'Use  protocolname as the X authority protocol to use.'
complete -c xvfb-run -s s -l server-args --description 'Pass  arguments to the  Xvfb server.'
complete -c xvfb-run -s w -l wait --description 'Ignored for compatibility with earlier versions.  ENVIRONMENT.'
complete -c xvfb-run -o faces --description 'argument) inside the Xvfb X server, configured … [See Man Page]'

