# apvlv
# Autogenerated from man page /usr/share/man/man1/apvlv.1.gz
# using Darwin man parser
complete -c apvlv -s c --description 'Load configuration from file instead of the default ~/.'
complete -c apvlv -s h --description 'Show help message and exit.'
complete -c apvlv -s v --description 'Show version and exit El COMMANDS The following… [See Man Page]'

