# arj-register
# Autogenerated from man page /usr/share/man/man1/arj-register.1.gz
# using Deroffing man parser
complete -c arj-register -o arj --description 'Registers all ARJ for Linux programs in the current directory.'
complete -c arj-register -o arj32 --description 'Registers all ARJ32 (supplied by ARJ Software, Inc.'

