# bsh
# Autogenerated from man page /usr/share/man/man1/bsh.1.gz
# using Deroffing man parser
complete -c bsh -o classpath --description 'option which sets the value of the CLASSPATH en… [See Man Page]'

