# build-rdeps
# Autogenerated from man page /usr/share/man/man1/build-rdeps.1.gz
# using Type1
complete -c build-rdeps -s u -l update --description 'Run apt-get update before searching for build-depends.'
complete -c build-rdeps -s s -l sudo --description 'Use sudo when running apt-get update.'
complete -c build-rdeps -l distribution --description 'Select another distribution, which is searched … [See Man Page]'
complete -c build-rdeps -l only-main --description 'Ignore contrib and non-free.'
complete -c build-rdeps -l exclude-component --description 'Ignore the given component (e. g.  main, contrib, non-free).'
complete -c build-rdeps -l origin --description 'Restrict the search to only the specified origi… [See Man Page]'
complete -c build-rdeps -s m -l print-maintainer --description 'Print the value of the maintainer field for each package.'
complete -c build-rdeps -s d -l debug --description 'Run the debug mode.'
complete -c build-rdeps -l help --description 'Show the usage information.'

