# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
# using Deroffing man parser
complete -c chfn -s f -l full-name --description 'Change the user\\*(Aqs full name.'
complete -c chfn -s h -l home-phone --description 'Change the user\\*(Aqs home phone number.'
complete -c chfn -s o -l other --description 'Change the user\\*(Aqs other GECOS information.'
complete -c chfn -s r -l room --description 'Change the user\\*(Aqs room number.'
complete -c chfn -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c chfn -s u -l help --description 'Display help message and exit.'
complete -c chfn -s w -l work-phone --description 'Change the user\\*(Aqs office phone number.'

