# ckbcomp
# Autogenerated from man page /usr/share/man/man1/ckbcomp.1.gz
# using Deroffing man parser
complete -c ckbcomp -s '?' -o help --description 'Print a usage message and exit.'
complete -c ckbcomp -o charmap --description 'The encoding to use for the output keymap.'
complete -c ckbcomp -s I --description 'Look in the top-level directory  dir for files … [See Man Page]'
complete -c ckbcomp -s v --description 'Set level of detail for listing.'
complete -c ckbcomp -o compact --description 'Generate a compact keymap with at most two xkb … [See Man Page]'
complete -c ckbcomp -o freebsd --description 'Generate a keymap for FreeBSD.'
complete -c ckbcomp -o backspace --description 'Specifies the behaviour of the . SM <BackSpace> and .'
complete -c ckbcomp -o symbols --description 'Specifies the symbols component name of the XKB… [See Man Page]'
complete -c ckbcomp -o keycodes --description 'Specifies the keycodes component name of the XK… [See Man Page]'
complete -c ckbcomp -o rules --description 'The name of the rules file to use.'
complete -c ckbcomp -o model --description 'Specifies the keyboard model used to choose the… [See Man Page]'
complete -c ckbcomp -o layout --description 'Specifies the layout used to choose the component names.'
complete -c ckbcomp -o variant --description 'Specifies the layout variant used to choose the… [See Man Page]'
complete -c ckbcomp -o option --description 'Adds an option used to choose component names.'

