# clojure1
# Autogenerated from man page /usr/share/man/man1/clojure1.4.1.gz
# using Deroffing man parser
complete -c clojure1 -o cp -o classpath --description 'Specifies additional classpath elements.'
complete -c clojure1 -s i -l init --description 'Load a file or resource at initialisation time.'
complete -c clojure1 -s e -l eval --description 'Evaluate expressions in string; print non-nil values.'
complete -c clojure1 -s r -l repl --description 'Run a repl.'
complete -c clojure1 -s h -s '?' -l help --description 'Print a help message and exit PATH ARGUMENTS A … [See Man Page]'

