# clojurec1
# Autogenerated from man page /usr/share/man/man1/clojurec1.4.1.gz
# using Deroffing man parser
complete -c clojurec1 -s d --description 'Specifies the destination directory for compiled class files.'
complete -c clojurec1 -s W -o Wreflect --description 'Causes the compiler to emit warnings when refle… [See Man Page]'
complete -c clojurec1 -o cp -o classpath --description 'Specifies additional classpath elements.'

