# cowpoke
# Autogenerated from man page /usr/share/man/man1/cowpoke.1.gz
# using Deroffing man parser
complete -c cowpoke -l arch --description 'Specify the Debian architecture(s) to build for.'
complete -c cowpoke -l dist --description 'Specify the Debian distribution(s) to build for.'
complete -c cowpoke -l buildd --description 'Specify the remote host to build on.'
complete -c cowpoke -l buildd-user --description 'Specify the remote user to build as.'
complete -c cowpoke -l create --description 'Create the remote cowbuilder root if it does not already exist.'
complete -c cowpoke -l return --description 'Copy results of the build to path.'
complete -c cowpoke -l no-return --description 'Do not copy results of the build to RETURN_DIR … [See Man Page]'
complete -c cowpoke -l dpkg-opts --description 'Specify additional options to be passed to dpkg… [See Man Page]'
complete -c cowpoke -l help --description 'Display a brief summary of the available option… [See Man Page]'
complete -c cowpoke -l version --description 'Display the current version information.'

