# cvs-debc
# Autogenerated from man page /usr/share/man/man1/cvs-debc.1.gz
# using Deroffing man parser
complete -c cvs-debc -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c cvs-debc -o Mmodule --description 'The name of the CVS module.'
complete -c cvs-debc -o Ppackage --description 'The name of the package.'
complete -c cvs-debc -o Vversion --description 'The version number of the package.'
complete -c cvs-debc -o Ttag --description 'The CVS tag to use for exporting sources.'
complete -c cvs-debc -o Rrootdirectory --description 'Root of the original sources archive.'
complete -c cvs-debc -o Wwork --description 'The full path name for the cvs-buildpackage working directory.'
complete -c cvs-debc -o xprefix --description 'This option provides the CVS default module prefix.'
complete -c cvs-debc -o Rroot --description 'Root of the original sources archive.'
complete -c cvs-debc -l help -l version --description 'Show help message and version information respectively.'

