# cvs-debuild
# Autogenerated from man page /usr/share/man/man1/cvs-debuild.1.gz
# using Deroffing man parser
complete -c cvs-debuild -l no-conf -l noconf --description '.'
complete -c cvs-debuild -l rootcmd -s r --description '.'
complete -c cvs-debuild -l preserve-env --description '.'
complete -c cvs-debuild -l preserve-envvar -s e --description '.'
complete -c cvs-debuild -l set-envvar --description '.'
complete -c cvs-debuild -l lintian -l no-lintian --description '.'
complete -c cvs-debuild -l ignore-dirname -l check-dirname --description 'These should not be needed, but it is provided nevertheless.'

