# data2inc
# Autogenerated from man page /usr/share/man/man1/data2inc.1.gz
# using Deroffing man parser
complete -c data2inc -s A --description 'Write bytes instead of characters.'
complete -c data2inc -s B --description 'If this option is given, the   msgfile will be … [See Man Page]'
complete -c data2inc -s H --description 'emit a small helptext.'
complete -c data2inc -s S --description 'data2inc will write the output as an array of s… [See Man Page]'
complete -c data2inc -s V --description 'Show the version number and exit.'

