# dcmd
# Autogenerated from man page /usr/share/man/man1/dcmd.1.gz
# using Deroffing man parser
complete -c dcmd -l dsc --description 'Select the . dsc file.'
complete -c dcmd -l schanges --description 'Select . changes files for the \'source\' architecture.'
complete -c dcmd -l bchanges --description 'Select . changes files for binary architectures.'
complete -c dcmd -l changes --description 'Select . changes files.  Implies --schanges and --bchanges.'
complete -c dcmd -l archdeb --description 'Select architecture-dependent binary packages (. deb files).'
complete -c dcmd -l indepdeb --description 'Select architecture-independent binary packages (. deb files).'
complete -c dcmd -l deb --description 'Select binary packages (. deb files).'
complete -c dcmd -l archudeb --description 'Select architecture-dependent udeb binary packages.'
complete -c dcmd -l indepudeb --description 'Select architecture-independent udeb binary packages.'
complete -c dcmd -l udeb --description 'Select udeb binary packages.'
complete -c dcmd -l tar -l orig --description 'Select the tar file.'
complete -c dcmd -l diff --description 'Select the Debian diff file.'
complete -c dcmd -l no-fail-on-missing -s r --description 'If any of the requested files were not found, d… [See Man Page]'

