# dcontrol
# Autogenerated from man page /usr/share/man/man1/dcontrol.1.gz
# using Type1
complete -c dcontrol -s s -l show-suites --description 'Add headers showing which distribution the cont… [See Man Page]'
complete -c dcontrol -s d -l debug --description 'Print \\s-1URL\\s0 queried.'
complete -c dcontrol -s h -l help --description 'Show a help message.'

