# dd-list
# Autogenerated from man page /usr/share/man/man1/dd-list.1.gz
# using Deroffing man parser
complete -c dd-list -s h -l help --description 'Print brief help message.'
complete -c dd-list -s i -l stdin --description 'Read package names from the standard input, ins… [See Man Page]'
complete -c dd-list -s d -l dctrl --description 'Read package list from standard input in the fo… [See Man Page]'
complete -c dd-list -s s -l sources --description 'Read package information from the specified Sources_files.'
complete -c dd-list -s u -l uploaders --description 'Also list developers who are named as uploaders… [See Man Page]'
complete -c dd-list -o nou -l nouploaders --description 'Only list package Maintainers, do not list Uploaders.'
complete -c dd-list -s b -l print-binary --description 'Use binary package names in the output instead … [See Man Page]'
complete -c dd-list -s V -l version --description 'Print the version.'

