# deb-reversion
# Autogenerated from man page /usr/share/man/man1/deb-reversion.1.gz
# using Deroffing man parser
complete -c deb-reversion -s v -l new-version --description 'Specifies the version number to be used for the new version.'
complete -c deb-reversion -s o -l old-version --description 'Specifies the version number to be used as the … [See Man Page]'
complete -c deb-reversion -s c -l calculate-only --description 'Only calculate and display the new version numb… [See Man Page]'
complete -c deb-reversion -s s -l string --description 'Instead of using \\*(AqLOCAL.'
complete -c deb-reversion -s k -l hook --description 'A hook command to run after unpacking the old .'
complete -c deb-reversion -s D -l debug --description 'Pass --debug to dpkg-deb(1).'
complete -c deb-reversion -s b -l force-bad-version --description 'Pass --force-bad-version to dch(1).'
complete -c deb-reversion -s h -l help --description 'Display usage information.'
complete -c deb-reversion -s V -l version --description 'Display version information.'
complete -c deb-reversion -s a --description 'deb-reversion command line and dch will be call… [See Man Page]'
complete -c deb-reversion -o 'v.' --description '.'

