# debclean
# Autogenerated from man page /usr/share/man/man1/debclean.1.gz
# using Deroffing man parser
complete -c debclean -l cleandebs --description 'Also remove all . deb, . changes and .'
complete -c debclean -l nocleandebs --description 'Do not remove the . deb, . changes and .'
complete -c debclean -l check-dirname-level --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debclean -l check-dirname-regex --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debclean -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c debclean -s d --description 'Do not run dpkg-checkbuilddeps to check build dependencies.'
complete -c debclean -l help --description 'Display a help message and exit successfully.'
complete -c debclean -l version --description 'Display version and copyright information and e… [See Man Page]'

