# debi
# Autogenerated from man page /usr/share/man/man1/debi.1.gz
# using Deroffing man parser
complete -c debi -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c debi -l debs-dir --description 'Look for the . changes and .'
complete -c debi -s m -l multi --description 'Search for a multiarch .'
complete -c debi -s u -l upgrade --description 'Only upgrade packages already installed on the … [See Man Page]'
complete -c debi -l check-dirname-level --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debi -l check-dirname-regex --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debi -l with-depends --description 'Attempt to satisfy the Depends of a package when installing it.'
complete -c debi -l tool --description 'Use the specified tool for installing the depen… [See Man Page]'
complete -c debi -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c debi -l help -l version --description 'Show help message and version information respectively.'

