# debrelease
# Autogenerated from man page /usr/share/man/man1/debrelease.1.gz
# using Deroffing man parser
complete -c debrelease -l dupload -l dput --description 'This specifies which uploader program to use; t… [See Man Page]'
complete -c debrelease -s S --description 'If this option is used, or the default .'
complete -c debrelease -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c debrelease -l multi --description 'Multiarch changes mode: This signifies that deb… [See Man Page]'
complete -c debrelease -l debs-dir --description 'Look for the . changes and .'
complete -c debrelease -l check-dirname-level --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debrelease -l check-dirname-regex --description 'See the above section Directory name checking f… [See Man Page]'
complete -c debrelease -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c debrelease -l help -s h --description 'Display a help message and exit successfully.'
complete -c debrelease -l version --description 'Display version and copyright information and e… [See Man Page]'

