# debrsign
# Autogenerated from man page /usr/share/man/man1/debrsign.1.gz
# using Deroffing man parser
complete -c debrsign -s S --description 'Look for a source-only .'
complete -c debrsign -o adebian-architecture -o tGNU-system-type --description 'See dpkg-architecture(1) for a description of these options.'
complete -c debrsign -l multi --description 'Multiarch changes mode: This signifies that deb… [See Man Page]'
complete -c debrsign -l path --description 'Specify a path to the GPG binary on the remote host.'
complete -c debrsign -l help -l version --description 'Show help message and version information respectively.'

