# defoma-subst
# Autogenerated from man page /usr/share/man/man1/defoma-subst.1.gz
# using Deroffing man parser
complete -c defoma-subst -s t --description 'Exit with true value (0) even if error occurs.'
complete -c defoma-subst -s v --description 'Verbose output.'
complete -c defoma-subst -s d --description 'More verbose output.'
complete -c defoma-subst -s q --description 'Quiet output.  EXAMPLES 1.  Create foo.'

