# dget
# Autogenerated from man page /usr/share/man/man1/dget.1.gz
# using Type1
complete -c dget -s b -l backup --description 'Move files that would be overwritten to . /backup.'
complete -c dget -s q -l quiet --description 'Suppress wget/curl non-error output.'
complete -c dget -s d -l download-only --description 'Do not run dpkg-source -x on the downloaded source package.'
complete -c dget -s x -l extract --description 'Run dpkg-source -x on the downloaded source pac… [See Man Page]'
complete -c dget -s u -l allow-unauthenticated --description 'Do not attempt to verify the integrity of downl… [See Man Page]'
complete -c dget -l build --description 'Run dpkg-buildpackage -b -uc on the downloaded source package.'
complete -c dget -l path --description 'In addition to /var/cache/apt/archives, dget us… [See Man Page]'
complete -c dget -l insecure --description 'Allow \\s-1SSL\\s0 connections to untrusted hosts.'
complete -c dget -l no-cache --description 'Bypass server-side \\s-1HTTP\\s0 caches by sendin… [See Man Page]'
complete -c dget -s h -l help --description 'Show a help message.'

