# dh_installdefoma
# Autogenerated from man page /usr/share/man/man1/dh_installdefoma.1.gz
# using Deroffing man parser
complete -c dh_installdefoma -s n -l noscripts --description 'Do not modify postinst/postrm scripts.'

