# dh_python3
# Autogenerated from man page /usr/share/man/man1/dh_python3.1.gz
# using Deroffing man parser
complete -c dh_python3 -l version --description 'show program\'s version number and exit.'
complete -c dh_python3 -s h -l help --description 'show this help message and exit.'
complete -c dh_python3 -l no-guessing-deps --description 'disable guessing dependencies.'
complete -c dh_python3 -l no-dbg-cleaning --description 'do not remove any files from debug packages.'
complete -c dh_python3 -l skip-private --description 'don\'t check private directories.'
complete -c dh_python3 -s v -l verbose --description 'turn verbose mode on.'
complete -c dh_python3 -s i -l indep --description 'act on architecture independent packages.'
complete -c dh_python3 -s a -l arch --description 'act on architecture dependent packages.'
complete -c dh_python3 -s q -l quiet --description 'be quiet.'
complete -c dh_python3 -s p -l package --description 'act on the package named PACKAGE.'
complete -c dh_python3 -s N -l no-package --description 'do not act on the specified package.'
complete -c dh_python3 -s V --description 'specify list of supported Python versions.'
complete -c dh_python3 -s X -l exclude --description 'exclude items that match given REGEXPR.'
complete -c dh_python3 -l compile-all --description 'compile all files from given private directory … [See Man Page]'
complete -c dh_python3 -l depends --description 'translate given requirements into Debian depend… [See Man Page]'
complete -c dh_python3 -l recommends --description 'translate given requirements into Debian depend… [See Man Page]'
complete -c dh_python3 -l suggests --description 'translate given requirements into Debian depend… [See Man Page]'

