# diameterc
# Autogenerated from man page /usr/share/man/man1/diameterc.1.gz
# using Deroffing man parser
complete -c diameterc -s o --description 'Specifies the directory into which the generate… [See Man Page]'
complete -c diameterc -s i --description 'Specifies a directory to add to the code path.'
complete -c diameterc -o E: --description 'Supresses erl generation.'
complete -c diameterc -o H: --description 'Supresses hrl generation.'
complete -c diameterc -l name --description 'Set @name in the dictionary file.'
complete -c diameterc -l prefix --description 'Set @prefix in the dictionary file.'
complete -c diameterc -l inherits --description 'Append an @inherits to the dictionary file.'

