# directfb-config
# Autogenerated from man page /usr/share/man/man1/directfb-config.1.gz
# using Deroffing man parser
complete -c directfb-config -l version --description 'Print the currently installed version of direct… [See Man Page]'
complete -c directfb-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c directfb-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c directfb-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c directfb-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c directfb-config -l input --description 'Print the linker flags necessary to statically … [See Man Page]'
complete -c directfb-config -l graphics --description 'Print the linker flags necessary to statically … [See Man Page]'
complete -c directfb-config -l fonts --description 'Print the linker flags necessary to statically … [See Man Page]'
complete -c directfb-config -l imageprovider --description 'Print the linker flags necessary to statically … [See Man Page]'
complete -c directfb-config -l videoprovider --description 'Print the linker flags necessary to statically … [See Man Page]'

