# dpkg-checkdeps
# Autogenerated from man page /usr/share/man/man1/dpkg-checkdeps.1.gz
# using Deroffing man parser
complete -c dpkg-checkdeps -l to --description 'PD Specify target packages-file.'
complete -c dpkg-checkdeps -l from --description 'PD Specify source packages-file.'
complete -c dpkg-checkdeps -l all --description 'PD Select all packages in source packages-file.'
complete -c dpkg-checkdeps -l arch --description 'PD Specify acceptable arch in packages-file.'
complete -c dpkg-checkdeps -l check --description 'PD Check selected packages are satisfied by all… [See Man Page]'
complete -c dpkg-checkdeps -l verbose --description 'PD Verbose mode.'
complete -c dpkg-checkdeps -s t --description '.'
complete -c dpkg-checkdeps -s f --description '.'
complete -c dpkg-checkdeps -s A --description '.'
complete -c dpkg-checkdeps -s a --description '.'
complete -c dpkg-checkdeps -s c --description '.'
complete -c dpkg-checkdeps -s v --description '.'
complete -c dpkg-checkdeps -s h --description '.'
complete -c dpkg-checkdeps -l help --description '.'

