# dscverify
# Autogenerated from man page /usr/share/man/man1/dscverify.1.gz
# using Deroffing man parser
complete -c dscverify -l keyring --description 'Add keyring to the list of keyrings to be used.'
complete -c dscverify -l no-default-keyrings --description 'Do not use the default set of keyrings.'
complete -c dscverify -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c dscverify -l nosigcheck -l no-sig-check -s u --description 'Skip the signature verification step.'
complete -c dscverify -l verbose --description 'Do not suppress GPG output.'
complete -c dscverify -l help -s h --description 'Display a help message and exit successfully.'
complete -c dscverify -l version --description 'Display version and copyright information and e… [See Man Page]'

