# fc-cache
# Autogenerated from man page /usr/share/man/man1/fc-cache.1.gz
# using Type1
complete -c fc-cache -s f -l force --description 'Force re-generation of apparently up-to-date ca… [See Man Page]'
complete -c fc-cache -s r -l really-force --description 'Erase all existing cache files and rescan.'
complete -c fc-cache -s s -l system-only --description 'Only scan system-wide directories, omitting the… [See Man Page]'
complete -c fc-cache -s v -l verbose --description 'Display status information while busy.'
complete -c fc-cache -s h -l help --description 'Show summary of options.'
complete -c fc-cache -s V -l version --description 'Show version of the program and exit.'

