# filezilla
# Autogenerated from man page /usr/share/man/man1/filezilla.1.gz
# using Deroffing man parser
complete -c filezilla -s c -l site --description 'Connect to the given site from the Site Manager.'
complete -c filezilla -s h -l help --description 'Displays a help dialog listing these commandline options.'
complete -c filezilla -s l -l logontype --description 'Set a special logontype, can only be used in co… [See Man Page]'
complete -c filezilla -s s -l sitemanager --description 'Start with Site Manager opened.'
complete -c filezilla -s v -l version --description 'Display version number of FileZilla.  ENVIRONMENT.'

