# fprcp-2
# Autogenerated from man page /usr/share/man/man1/fprcp-2.6.0.1.gz
# using Deroffing man parser
complete -c fprcp-2 -s C --description 'Define the symbol   symbol before processing is started.'
complete -c fprcp-2 -s i --description 'Specify the input file name.  This argument is mandatory.'
complete -c fprcp-2 -s l --description 'Set the programming language for include files.'
complete -c fprcp-2 -s n --description 'Do not support nested comments.'
complete -c fprcp-2 -s p --description 'Set the include path.'

