# gacutil2
# Autogenerated from man page /usr/share/man/man1/gacutil2.1.gz
# using Deroffing man parser
complete -c gacutil2 -o package --description '.'
complete -c gacutil2 -s i --description '.'
complete -c gacutil2 -s l --description '.'
complete -c gacutil2 -s u --description '.'
complete -c gacutil2 -o us --description 'Uninstalls an assembly using the specified asse… [See Man Page]'
complete -c gacutil2 -o ul --description 'Uninstalls one or more assemblies from the glob… [See Man Page]'

