# getbuildlog
# Autogenerated from man page /usr/share/man/man1/getbuildlog.1.gz
# using Deroffing man parser
complete -c getbuildlog -s h -l help --description 'Show usage information and examples.'
complete -c getbuildlog -s V -l version --description 'Show version and copyright information.  EXAMPLES.'

