# gml2gv
# Autogenerated from man page /usr/share/man/man1/gml2gv.1.gz
# using Deroffing man parser
complete -c gml2gv -s '?' --description 'Prints usage information and exits.'
complete -c gml2gv -s o --description 'Prints output to the file outfile.'

