# go-get
# Autogenerated from man page /usr/share/man/man1/go-get.1.gz
# using Deroffing man parser
complete -c go-get -s a -s n -s v -s x -s p --description 'The -a, -n, -v, -x, and -p flags have the same … [See Man Page]'
complete -c go-get -s d --description 'The -d flag instructs get to stop after downloa… [See Man Page]'
complete -c go-get -o fix --description 'The -fix flag instructs get to run the fix tool… [See Man Page]'
complete -c go-get -s u --description 'The -u flag instructs get to use the network to… [See Man Page]'

