# go-test
# Autogenerated from man page /usr/share/man/man1/go-test.1.gz
# using Deroffing man parser
complete -c go-test -s c --description 'Compile the test binary to pkg. test but do not run it.'
complete -c go-test -s i --description 'Install packages that are dependencies of the test.'

