# go-vet
# Autogenerated from man page /usr/share/man/man1/go-vet.1.gz
# using Deroffing man parser
complete -c go-vet -s n --description 'The -n flag causes tool to print the command th… [See Man Page]'
complete -c go-vet -s x --description 'The -x flag causes clean to print remove comman… [See Man Page]'

