# gpscat
# Autogenerated from man page /usr/share/man/man1/gpscat.1.gz
# using Deroffing man parser
complete -c gpscat -s p --description '.'
complete -c gpscat -s s --description '.'
complete -c gpscat -s t --description '.'
complete -c gpscat -s D --description '.'
complete -c gpscat -s h --description '.'

