# gpsctl
# Autogenerated from man page /usr/share/man/man1/gpsctl.1.gz
# using Deroffing man parser
complete -c gpsctl -s b --description '.'
complete -c gpsctl -s c --description '.'
complete -c gpsctl -s e --description '.'
complete -c gpsctl -s t --description 'option without specifying a device.'
complete -c gpsctl -s f --description '.'
complete -c gpsctl -s l --description '.'
complete -c gpsctl -s n --description '.'
complete -c gpsctl -s s --description '.'
complete -c gpsctl -s x --description '.'
complete -c gpsctl -o 'f.' --description '.'
complete -c gpsctl -s T --description '.'
complete -c gpsctl -s h --description '.'
complete -c gpsctl -s D --description '.'
complete -c gpsctl -s V --description '.'

