# grep-excuses
# Autogenerated from man page /usr/share/man/man1/grep-excuses.1.gz
# using Deroffing man parser
complete -c grep-excuses -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c grep-excuses -l wipnity -s w --description 'Get information from <http://release. debian. org/migration/>.'
complete -c grep-excuses -l help --description 'Show a brief usage message.'
complete -c grep-excuses -l version --description 'Show version and copyright information.'

