# gxl2dot
# Autogenerated from man page /usr/share/man/man1/gxl2dot.1.gz
# using Deroffing man parser
complete -c gxl2dot -s g --description 'The command name and input file extensions are … [See Man Page]'
complete -c gxl2dot -s d --description 'The command name and input file extensions are … [See Man Page]'
complete -c gxl2dot -s '?' --description 'Prints usage information and exits.'
complete -c gxl2dot -s o --description 'If specified, the output will be written into the file outfile.'

