# h2paspp
# Autogenerated from man page /usr/share/man/man1/h2paspp.1.gz
# using Deroffing man parser
complete -c h2paspp -o dsymbol --description 'Define the symbol   symbol before processing is started.'
complete -c h2paspp -s h --description 'emit a small helptext.'
complete -c h2paspp -s I --description 'option was given, in which case the include fil… [See Man Page]'
complete -c h2paspp -s o --description 'option is given, in which case the file is writ… [See Man Page]'
complete -c h2paspp -o ooutfile --description 'If this option is given, the output will be wri… [See Man Page]'

