# h2pas-2
# Autogenerated from man page /usr/share/man/man1/h2pas-2.6.0.1.gz
# using Deroffing man parser
complete -c h2pas-2 -s d --description 'use   external; for all procedure and function declarations.'
complete -c h2pas-2 -s D --description 'use   external  libname   name  \'func\\_name\' fo… [See Man Page]'
complete -c h2pas-2 -s e --description 'Emit a series of constants instead of an enumer… [See Man Page]'
complete -c h2pas-2 -s i --description 'create an include file instead of a unit (omits… [See Man Page]'
complete -c h2pas-2 -s l --description 'specify the library name for external function declarations.'
complete -c h2pas-2 -s o --description 'Specify the output file name.'
complete -c h2pas-2 -s p --description 'use the letter    P in front of pointer type pa… [See Man Page]'
complete -c h2pas-2 -s s --description 'Strip comments from the input file.'
complete -c h2pas-2 -s t --description 'prepend typedef type names with the letter  T (… [See Man Page]'
complete -c h2pas-2 -s v --description 'replace pointer parameters by call by reference parameters.'
complete -c h2pas-2 -s w --description 'Header file is a win32 header file (adds suppor… [See Man Page]'
complete -c h2pas-2 -s x --description 'handle SYS_TRAP of the PalmOS header files.'

