# hal-find-by-property
# Autogenerated from man page /usr/share/man/man1/hal-find-by-property.1.gz
# using Deroffing man parser
complete -c hal-find-by-property -l key --description 'The name of the property.'
complete -c hal-find-by-property -l string --description 'String value of the property.'
complete -c hal-find-by-property -l verbose --description 'Verbose output.'
complete -c hal-find-by-property -l help --description 'Print out usage.'
complete -c hal-find-by-property -l version --description 'Print the version.'

