# hal-set-property
# Autogenerated from man page /usr/share/man/man1/hal-set-property.1.gz
# using Deroffing man parser
complete -c hal-set-property -l udi --description 'The UDI (Unique Device Identifier) of the device object.'
complete -c hal-set-property -l key --description 'The name of the property.'
complete -c hal-set-property -l int --description 'Set value property of the property to a 32-bit signed integer.'
complete -c hal-set-property -l uint64 --description 'Set value property of the property to a 64-bit … [See Man Page]'
complete -c hal-set-property -l string --description 'Set value property of the property to a string.'
complete -c hal-set-property -l double --description 'Set value property of the property to a floating point number.'
complete -c hal-set-property -l bool --description 'Set value property of the property to boolean, e. g.'
complete -c hal-set-property -l strlist-pre --description 'Prepend an item to a string list.'
complete -c hal-set-property -l strlist-post --description 'Append an item to a string list.'
complete -c hal-set-property -l strlist-rem --description 'Remove an item from a string list.'
complete -c hal-set-property -l remove --description 'Remove a property.'
complete -c hal-set-property -l help --description 'Print out usage.'
complete -c hal-set-property -l version --description 'Print the version.'

