# hal-lock
# Autogenerated from man page /usr/share/man/man1/hal-lock.1.gz
# using Deroffing man parser
complete -c hal-lock -l interface --description 'The name of the interface to lock.'
complete -c hal-lock -l run --description 'Program to run if the lock was acquired.'
complete -c hal-lock -l udi --description 'The UDI (Unique Device Identifier) of the device object.'
complete -c hal-lock -l exclusive --description 'Whether the lock can be held by others.'
complete -c hal-lock -l exit-with-lock --description 'Kill the program if the acquired lock is lost.'
complete -c hal-lock -l exit-with-dev --description 'Kill the program if the device is removed.'
complete -c hal-lock -l help --description 'Print out usage.'
complete -c hal-lock -l version --description 'Print the version.'

