# hal-get-property
# Autogenerated from man page /usr/share/man/man1/hal-get-property.1.gz
# using Deroffing man parser
complete -c hal-get-property -l udi --description 'The UDI (Unique Device Identifier) of the device object.'
complete -c hal-get-property -l key --description 'The name of the property.'
complete -c hal-get-property -l hex --description 'Show int32/uint64 values in hex (without a leading 0x).'
complete -c hal-get-property -l verbose --description 'Verbose output.'
complete -c hal-get-property -l help --description 'Print out usage.'
complete -c hal-get-property -l version --description 'Print the version.'

