# hp-clean
# Autogenerated from man page /usr/share/man/man1/hp-clean.1.gz
# using Deroffing man parser
complete -c hp-clean -o 'd<device-uri>' -l device --description 'To specify a CUPS printer:.'
complete -c hp-clean -o 'p<printer>' -l printer --description 'MODE Run in graphical UI mode:.'
complete -c hp-clean -s u -l gui --description 'Run in interactive mode:.'
complete -c hp-clean -s i -l interactive --description 'OPTIONS Use Qt4:.'
complete -c hp-clean -l qt4 --description 'Set the logging level:.'
complete -c hp-clean -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*defa… [See Man Page]'
complete -c hp-clean -s g -o 'ldebug)' --description 'This help information:.'
complete -c hp-clean -s h -l help --description 'SEE ALSO hp-align hp-clean hp-linefeedcal hp-pq… [See Man Page]'

