# javaws
# Autogenerated from man page /usr/share/man/man1/javaws.1.gz
# using Deroffing man parser
complete -c javaws -o offline --description 'Run Java Web Start in offline mode.'
complete -c javaws -o Xnosplash --description 'Do not display the initial splash screen.'
complete -c javaws -o open --description 'If specified, replaces the arguments in the jnl… [See Man Page]'
complete -c javaws -o print --description 'If specified, replaces the arguments in the jnl… [See Man Page]'
complete -c javaws -o online --description 'Use online mode (default behavior).'
complete -c javaws -o wait --description 'If specified, the javaws process will not exit … [See Man Page]'
complete -c javaws -o verbose --description 'Display additional output.'
complete -c javaws -o 'J<option>' --description 'Supply options to the VM.'
complete -c javaws -o system --description 'Run the application from the system cache only.'
complete -c javaws -o viewer --description 'Show the Cache Viewer in the Java Control Panel.'
complete -c javaws -o clearcache --description 'Remove all non-installed applications from the cache.'
complete -c javaws -o userConfig --description 'Clear the specified deployment property.'
complete -c javaws -o uninstall --description 'Remove all applications from the cache.'
complete -c javaws -o import --description 'Import the application to the cache.'
complete -c javaws -o silent --description 'Import silently (with no user interface).'
complete -c javaws -o codebase --description 'Retrieve resources from the given codebase.'
complete -c javaws -o shortcut --description 'Install shortcuts as if user allowed prompt.'
complete -c javaws -o association --description 'Install associations as if user allowed prompt.'

