# jvisualvm
# Autogenerated from man page /usr/share/man/man1/jvisualvm.1.gz
# using Deroffing man parser
complete -c jvisualvm -o 'J<jvm_option>' --description 'Pass this <jvm_option> to the JVM software.'

