# lintian-info
# Autogenerated from man page /usr/share/man/man1/lintian-info.1.gz
# using Type1
complete -c lintian-info -s a -l annotate --description 'Read from standard input or any files specified… [See Man Page]'
complete -c lintian-info -s h -l help --description 'Display usage information and exit.'
complete -c lintian-info -l profile --description 'Use the severities from the vendor profile prof… [See Man Page]'

