# linux-version
# Autogenerated from man page /usr/share/man/man1/linux-version.1.gz
# using Deroffing man parser
complete -c linux-version -l paths --description 'AUTHOR linux-version and this manual page were … [See Man Page]'

