# list-unreleased
# Autogenerated from man page /usr/share/man/man1/list-unreleased.1.gz
# using Deroffing man parser
complete -c list-unreleased -s c --description 'Display pending changes.'
complete -c list-unreleased -s R --description 'Don\'t recurse into subdirectories looking for packages.'

