# lshal
# Autogenerated from man page /usr/share/man/man1/lshal.1.gz
# using Deroffing man parser
complete -c lshal -s m -l monitor --description 'Print changes emitted by the  hald daemon.'
complete -c lshal -s s -l short --description 'Short output.'
complete -c lshal -s t -l tree --description 'Display the devices organized in a tree.'
complete -c lshal -s u -l show --description 'Show only the given UDI (Unique Device Identifier).'
complete -c lshal -s h -l help --description 'Print out usage.'
complete -c lshal -s V -l version --description 'Print the version.'

