# mass-bug
# Autogenerated from man page /usr/share/man/man1/mass-bug.1.gz
# using Type1
complete -c mass-bug -l severity --description 'Specify the severity with which bugs should be filed.'
complete -c mass-bug -l display --description 'Fill out the templates for each package and dis… [See Man Page]'
complete -c mass-bug -l send --description 'Actually send the bug reports. ie n.'
complete -c mass-bug -l subject --description 'el.'
complete -c mass-bug -l tags --description 'Set the \\s-1BTS\\s0 pseudo-header for tags.'
complete -c mass-bug -l user --description 'Set the \\s-1BTS\\s0 pseudo-header for a usertags\' user.'
complete -c mass-bug -l usertags --description 'Set the \\s-1BTS\\s0 pseudo-header for usertags.'
complete -c mass-bug -l source --description 'Specify that package names refer to source pack… [See Man Page]'
complete -c mass-bug -l sendmail --description 'Specify the sendmail command.'
complete -c mass-bug -l no-wrap --description 'Do not wrap the template to lines of 70 characters.'
complete -c mass-bug -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c mass-bug -l help --description 'Provide a usage message.'

