# mdiff
# Autogenerated from man page /usr/share/man/man1/mdiff.1.gz
# using Deroffing man parser
complete -c mdiff -s h --description '(ignored).'
complete -c mdiff -s v -l verbose --description 'report a few statistics on stderr.'
complete -c mdiff -l help --description 'display this help then exit.'
complete -c mdiff -l version --description 'display program version then exit . SS "Formatting output:".'
complete -c mdiff -s T -l initial-tab --description 'produce TAB instead of initial space.'
complete -c mdiff -s l -l paginate --description 'paginate output through `pr\'.'
complete -c mdiff -s S -l 'string[' --description 'take note of another user STRING.'
complete -c mdiff -s V -l show-links --description 'give file and line references in annotations.'
complete -c mdiff -s t -l expand-tabs --description 'expand tabs to spaces in the output . SS "Debugging:".'
complete -c mdiff -s 0 -l debugging --description 'output many details about what is going on .'
complete -c mdiff -s 1 -l no-deleted --description 'inhibit output of deleted words.'
complete -c mdiff -s 2 -l no-inserted --description 'inhibit output of inserted words.'
complete -c mdiff -s 3 -l no-common --description 'inhibit output of common words.'
complete -c mdiff -s A -l auto-pager --description 'automatically calls a pager.'
complete -c mdiff -s k -l less-mode --description 'variation of printer mode for "less".'
complete -c mdiff -s m -l avoid-wraps --description 'do not extend fields through newlines.'
complete -c mdiff -s o -l printer --description 'overstrike as for printers.'
complete -c mdiff -s z -l terminal --description 'use termcap as for terminal displays.'
complete -c mdiff -s O -l item-regexp --description 'compare items as defined by REGEXP.'
complete -c mdiff -s W -l word-mode --description 'compare words instead of lines.'

