# mdm
# Autogenerated from man page /usr/share/man/man1/mdm.1.gz
# using Deroffing man parser
complete -c mdm -o nodaemon --description 'Do not fork into the background.'
complete -c mdm -l no-console --description 'No console (local) servers to be run.'
complete -c mdm -l preserve-ld-vars --description 'Preserve LD_* variables.'
complete -c mdm -l version --description 'Print the MDM version.'
complete -c mdm -l help --description 'Print simple description of accepted options.'

