# mdtool
# Autogenerated from man page /usr/share/man/man1/mdtool.1.gz
# using Deroffing man parser
complete -c mdtool -s c -l configuration:CONFIGURATION --description 'Name of the solution configuration to build.'
complete -c mdtool -s t -l target:TARGET --description 'Name of the target: Clean or Build.'
complete -c mdtool -s p -l project:PROJECT --description 'Name of the project to build.'
complete -c mdtool -l simple-makefiles -s s --description 'Generates set of Makefiles with the most common… [See Man Page]'
complete -c mdtool -o d:default-config --description 'Configuration that the Makefile will build by default.'

