# meld
# Autogenerated from man page /usr/share/man/man1/meld.1.gz
# using Deroffing man parser
complete -c meld -l auto-compare -s a --description 'br Automatically compare all differing files on startup.'
complete -c meld -l diff --description 'br Create a diff tab for the given files or directories.'
complete -c meld -l help -s h --description 'br Print application help and usage.'
complete -c meld -l LABEL -s L --description 'br Set application window title to <label>.'
complete -c meld -l version --description '.'

