# minissdpd
# Autogenerated from man page /usr/share/man/man1/minissdpd.1.gz
# using Deroffing man parser
complete -c minissdpd -s d --description 'debug : do not go to background, output message… [See Man Page]'
complete -c minissdpd -s 6 --description 'IPv6 : Enable IPv6 in addition to IPv4.'
complete -c minissdpd -s s --description 'path of the unix socket open for communicating … [See Man Page]'
complete -c minissdpd -s p --description 'path of the file where pid is written at startup.'
complete -c minissdpd -s i --description 'name or IP address of the interface used to lis… [See Man Page]'

