# mongo
# Autogenerated from man page /usr/share/man/man1/mongo.1.gz
# using Type1
complete -c mongo -l shell --description 'run the shell after executing files.'
complete -c mongo -l help --description 'show usage information.'
complete -c mongo -l host --description 'server to connect to (default HOST=localhost).'
complete -c mongo -l port --description 'port to connect to (default PORT=27017).'
complete -c mongo -l nodb --description 'do not connect to mongod.'
complete -c mongo -l eval --description 'evaluate JavaScript.'
complete -c mongo -s u --description 'specify user to log in as.'

