# mongorestore
# Autogenerated from man page /usr/share/man/man1/mongorestore.1.gz
# using Type1
complete -c mongorestore -l help --description 'show usage information.'
complete -c mongorestore -s h -l host --description 'server to connect to (default HOST=localhost).'
complete -c mongorestore -s d -l db --description 'database to use.'
complete -c mongorestore -s c -l c --description 'collection to use.'
complete -c mongorestore -l dir --description 'directory from which to restore.'

