# mutt_dotlock
# Autogenerated from man page /usr/share/man/man1/mutt_dotlock.1.gz
# using Deroffing man parser
complete -c mutt_dotlock -s t --description 'Just try.'
complete -c mutt_dotlock -s f --description 'Force the lock.'
complete -c mutt_dotlock -s u --description 'Unlock.   mutt_dotlock  will remove file. lock.'
complete -c mutt_dotlock -s d --description 'Delete.'
complete -c mutt_dotlock -s p --description 'Use privileges.'
complete -c mutt_dotlock -s r --description 'This command line option tells  mutt_dotlock  t… [See Man Page]'

