# mysqlreport
# Autogenerated from man page /usr/share/man/man1/mysqlreport.1.gz
# using Deroffing man parser
complete -c mysqlreport -l help --description 'Output help information and exit.'
complete -c mysqlreport -l user --description '.'
complete -c mysqlreport -l password --description 'As of version 2.'
complete -c mysqlreport -l host --description '.'
complete -c mysqlreport -l port --description '.'
complete -c mysqlreport -l socket --description '.'
complete -c mysqlreport -l no-mycnf --description '.'
complete -c mysqlreport -l dtq --description 'Print Distribution of Total Queries (DTQ) repor… [See Man Page]'
complete -c mysqlreport -l dms --description 'Print Data Manipulation Statements (DMS) report… [See Man Page]'
complete -c mysqlreport -l com --description 'Print top N number of non-DMS Com_ status value… [See Man Page]'
complete -c mysqlreport -l sas --description 'Print report for Select_ and Sort_ status value… [See Man Page]'
complete -c mysqlreport -l tab --description 'Print Threads, Aborted, and Bytes status report… [See Man Page]'
complete -c mysqlreport -l qcache --description 'Print Query Cache report.'
complete -c mysqlreport -l all --description 'Equivalent to "--dtq --dms --com 3 --sas --qcache".'
complete -c mysqlreport -l infile --description 'Instead of getting SHOW STATUS values from MySQ… [See Man Page]'
complete -c mysqlreport -l outfile --description 'After printing the report to screen, print the … [See Man Page]'
complete -c mysqlreport -l email --description 'After printing the report to screen, email the … [See Man Page]'
complete -c mysqlreport -l flush-status --description 'Execute a "FLUSH STATUS;" after generating the reports.'

