# mysql_tableinfo
# Autogenerated from man page /usr/share/man/man1/mysql_tableinfo.1.gz
# using Type1
complete -c mysql_tableinfo -l clear --description 'Does \\s-1DROP\\s0 \\s-1TABLE\\s0 on the info table… [See Man Page]'
complete -c mysql_tableinfo -l clear-only --description 'Same as --clear but exits after the DROPs.'
complete -c mysql_tableinfo -l col --description 'Adds columns information (into table `col`).'
complete -c mysql_tableinfo -l idx --description 'Adds index information (into table `idx`).'
complete -c mysql_tableinfo -l prefix --description 'The info tables are named from the concatenatio… [See Man Page]'
complete -c mysql_tableinfo -s q -l quiet --description 'Does not warn you about what the script is goin… [See Man Page]'
complete -c mysql_tableinfo -l tbl-status --description 'Instead of using \\s-1SHOW\\s0 \\s-1TABLES\\s0, use… [See Man Page]'
complete -c mysql_tableinfo -l help --description 'Display helpscreen and exit.'
complete -c mysql_tableinfo -s u -l user --description 'user for database login if not current user.'
complete -c mysql_tableinfo -s p -l password --description 'password to use when connecting to server.'
complete -c mysql_tableinfo -s h -l host --description 'host to connect to.'
complete -c mysql_tableinfo -s P -l port --description 'port to use when connecting to server.'

