# nmudiff
# Autogenerated from man page /usr/share/man/man1/nmudiff.1.gz
# using Deroffing man parser
complete -c nmudiff -l new --description 'Instead of mailing the bug reports which are to… [See Man Page]'
complete -c nmudiff -l old --description 'Send the bug report to all of the bugs which ar… [See Man Page]'
complete -c nmudiff -l mutt --description 'Use mutt(1) for editing and sending the message… [See Man Page]'
complete -c nmudiff -l no-mutt --description 'Use sensible-editor(1) to edit the message and … [See Man Page]'
complete -c nmudiff -l sendmail --description 'Specify the sendmail command.'
complete -c nmudiff -l from --description 'If using the sendmail (--no-mutt) option, then … [See Man Page]'
complete -c nmudiff -l delay --description 'Indicate in the generated mail that the NMU has… [See Man Page]'
complete -c nmudiff -l no-delay -l nodelay --description 'Equivalent to --delay 0.'
complete -c nmudiff -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c nmudiff -l help --description 'Display a help message and exit successfully.'
complete -c nmudiff -s t --description 'devscripts configuration files; see below.'
complete -c nmudiff -l version --description 'Display version and copyright information and e… [See Man Page]'

