# pdfopen
# Autogenerated from man page /usr/share/man/man1/pdfopen.1.gz
# using Deroffing man parser
complete -c pdfopen -s h -l help --description 'output help and exit.'
complete -c pdfopen -s v -l version --description 'output the version number and exit.'
complete -c pdfopen -s r -l reset_focus --description 'after sending commands to the PDF viewer, attem… [See Man Page]'
complete -c pdfopen -o viewer --description '<ar9|ar9-tab|ar8|ar7|ar5|xpdf|evince> use (resp… [See Man Page]'
complete -c pdfopen -l page --description '<pagenumber> option.'

