# pip
# Autogenerated from man page /usr/share/man/man1/pip.1.gz
# using Deroffing man parser
complete -c pip -s h -l help --description 'Show summary of options.'
complete -c pip -l version --description 'Show the version of the program.'
complete -c pip -s v -l verbose --description 'Be more verbose.'
complete -c pip -s q -l quiet --description 'Be less verbose; suppress unimportant output.'
complete -c pip -l log --description 'Log file where a complete (maximum verbosity) r… [See Man Page]'
complete -c pip -l proxy --description 'Have pip use a proxy server to access sites.'
complete -c pip -l exists-action --description 'Default action when a path already exists.'
complete -c pip -l timeout --description 'Set the timeout for connecting to download sites, in seconds.'

