# plex
# Autogenerated from man page /usr/share/man/man1/plex.1.gz
# using Deroffing man parser
complete -c plex -s v --description 'Verbose:  plex generates a readable description… [See Man Page]'
complete -c plex -s o --description 'Optimize: plex optimizes DFA tables to produce a minimal DFA.'

