# plex-2
# Autogenerated from man page /usr/share/man/man1/plex-2.6.0.1.gz
# using Deroffing man parser
complete -c plex-2 -s v --description 'Verbose:  plex generates a readable description… [See Man Page]'
complete -c plex-2 -s o --description 'Optimize: plex optimizes DFA tables to produce a minimal DFA.'

