# plotchangelog
# Autogenerated from man page /usr/share/man/man1/plotchangelog.1.gz
# using Deroffing man parser
complete -c plotchangelog -s l -l linecount --description 'Instead of using the debian version number as t… [See Man Page]'
complete -c plotchangelog -s b -l bugcount --description 'Instead of using the debian version number as t… [See Man Page]'
complete -c plotchangelog -s c -l cumulative --description 'When used together with either  --bugcount or  … [See Man Page]'
complete -c plotchangelog -s v -l no-version --description 'Do not show upstream version labels.'
complete -c plotchangelog -s m -l no-maint --description 'Do not differentiate between different maintain… [See Man Page]'
complete -c plotchangelog -s s -l save --description 'Save the graph to file in postscript format ins… [See Man Page]'
complete -c plotchangelog -s u -l urgency --description 'Use larger points when displaying higher-urgenc… [See Man Page]'
complete -c plotchangelog -l verbose --description 'Output the gnuplot script that is fed into gnup… [See Man Page]'
complete -c plotchangelog -o gcommands -l gnuplot --description 'This allows you to insert  gnuplot (1) commands… [See Man Page]'
complete -c plotchangelog -l help --description 'Show a usage summary.'
complete -c plotchangelog -l version --description 'Display version, author and copyright information.'
complete -c plotchangelog -l noconf -l no-conf --description 'Do not read any configuration files (see below).'
complete -c plotchangelog -o 'b.' -s g --description 'may be ignored; see the next variable instead.'

