# postw32
# Autogenerated from man page /usr/share/man/man1/postw32.1.gz
# using Deroffing man parser
complete -c postw32 -s i --description 'specifies the input file to process.'
complete -c postw32 -s h --description 'Displays a short help message.'
complete -c postw32 -s m --description 'Set the subsystem (the application type) to eit… [See Man Page]'
complete -c postw32 -s s --description 'Set the stack size to   size bytes.'
complete -c postw32 -s v --description 'Be verbose about the operations that are performed.'
complete -c postw32 -l input --description 'option.'
complete -c postw32 -l help --description 'option.'
complete -c postw32 -l subsystem --description 'option.'
complete -c postw32 -l stack --description 'option.'
complete -c postw32 -l verbose --description 'option.'
complete -c postw32 -s V --description 'Set the version of the file to  M.'
complete -c postw32 -l version --description 'option.  SEE ALSO fpc (1) ppc386 (1).'

