# pts-subscribe
# Autogenerated from man page /usr/share/man/man1/pts-subscribe.1.gz
# using Deroffing man parser
complete -c pts-subscribe -l until -s u --description 'When at(1) should cancel the subscription.'
complete -c pts-subscribe -l forever --description 'Don\'t cancel the subscription automatically.'
complete -c pts-subscribe -l help -s h --description 'Display a help message and exit successfully.'
complete -c pts-subscribe -l version --description 'Display version and copyright information and e… [See Man Page]'

