# pts-unsubscribe
# Autogenerated from man page /usr/share/man/man1/pts-unsubscribe.1.gz
# using Deroffing man parser
complete -c pts-unsubscribe -l until -s u --description 'When at(1) should cancel the subscription.'
complete -c pts-unsubscribe -l forever --description 'Don\'t cancel the subscription automatically.'
complete -c pts-unsubscribe -l help -s h --description 'Display a help message and exit successfully.'
complete -c pts-unsubscribe -l version --description 'Display version and copyright information and e… [See Man Page]'

