# py3compile
# Autogenerated from man page /usr/share/man/man1/py3compile.1.gz
# using Deroffing man parser
complete -c py3compile -l version --description 'Show program\'s version number and exit.'
complete -c py3compile -s h -l help --description 'Show this help message and exit.'
complete -c py3compile -s f -l force --description 'Force rebuild of byte-code files even if timest… [See Man Page]'
complete -c py3compile -s O --description 'Byte-compile to . pyo files.'
complete -c py3compile -s q -l quiet --description 'Be quiet.'
complete -c py3compile -s v -l verbose --description 'Turn verbose mode on.'
complete -c py3compile -s p -l package --description 'Specify Debian package name whose files should be bytecompiled.'
complete -c py3compile -s V --description 'Force private modules to be bytecompiled with P… [See Man Page]'
complete -c py3compile -s X -l exclude --description 'exclude items that match given REGEXPR.'

