# pycolor
# Autogenerated from man page /usr/share/man/man1/pycolor.1.gz
# using Deroffing man parser
complete -c pycolor -s h -l help --description 'Output a brief help message.'
complete -c pycolor -s s -l scheme --description 'Give the color scheme to use.'

