# python3dmu-config
# Autogenerated from man page /usr/share/man/man1/python3dmu-config.1.gz
# using Deroffing man parser
complete -c python3dmu-config -l abiflags --description 'print the the ABI flags as specified by PEP 3149.'
complete -c python3dmu-config -l cflags --description 'print the C compiler flags.'
complete -c python3dmu-config -l ldflags --description 'print the flags that should be passed to the linker.'
complete -c python3dmu-config -l includes --description 'similar to --cflags but only with -I options (p… [See Man Page]'
complete -c python3dmu-config -l libs --description 'similar to --ldflags but only with -l options (used libraries).'
complete -c python3dmu-config -l prefix --description 'prints the prefix (base directory) under which … [See Man Page]'
complete -c python3dmu-config -l exec-prefix --description 'print the prefix used for executable program di… [See Man Page]'
complete -c python3dmu-config -l extension-suffix --description 'print the extension suffix used for binary extensions.'
complete -c python3dmu-config -l help --description 'print the usage message.'

