# python3mu
# Autogenerated from man page /usr/share/man/man1/python3mu.1.gz
# using Deroffing man parser
complete -c python3mu -s B --description 'Don\'t write . py[co] files on import.'
complete -c python3mu -s c --description 'Specify the command to execute (see next section).'
complete -c python3mu -s d --description 'Turn on parser debugging output (for wizards on… [See Man Page]'
complete -c python3mu -s E --description 'Ignore environment variables like PYTHONPATH an… [See Man Page]'
complete -c python3mu -s h -s '?' -l help --description 'Prints the usage for the interpreter executable and exits.'
complete -c python3mu -s i --description 'When a script is passed as first argument or th… [See Man Page]'
complete -c python3mu -s m --description 'Searches  sys.'
complete -c python3mu -s O --description 'Turn on basic optimizations.'
complete -c python3mu -o OO --description 'Discard docstrings in addition to the -O optimizations.'
complete -c python3mu -s q --description 'Do not print the version and copyright messages.'
complete -c python3mu -s R --description 'Turn on "hash randomization", so that the hash(… [See Man Page]'
complete -c python3mu -s Q --description 'Division control; see PEP 238.'
complete -c python3mu -s s --description 'Don\'t add user site directory to sys. path.'
complete -c python3mu -s S --description 'Disable the import of the module site and the s… [See Man Page]'
complete -c python3mu -s u --description 'Force the binary I/O layers of stdin, stdout an… [See Man Page]'
complete -c python3mu -s v --description 'Print a message each time a module is initializ… [See Man Page]'
complete -c python3mu -s V -l version --description 'Prints the Python version number of the executable and exits.'
complete -c python3mu -s W --description 'Warning control.'
complete -c python3mu -s x --description 'Skip the first line of the source.'

