# qbittorrent
# Autogenerated from man page /usr/share/man/man1/qbittorrent.1.gz
# using Deroffing man parser
complete -c qbittorrent -l help --description '.'
complete -c qbittorrent -l version --description '.'
complete -c qbittorrent -l no-splash --description '.'
complete -c qbittorrent -l webui-port --description '.'

