# resgen2
# Autogenerated from man page /usr/share/man/man1/resgen2.1.gz
# using Deroffing man parser
complete -c resgen2 -o compile --description 'Sp This switch instructs resgen to compile multiple files.'
complete -c resgen2 -o usesourcepath --description '.'

