# sctp_test
# Autogenerated from man page /usr/share/man/man1/sctp_test.1.gz
# using Deroffing man parser
complete -c sctp_test -s s --description 'Act as client.'
complete -c sctp_test -s l --description 'Listen for connections (server).'
complete -c sctp_test -s a --description 'assoc_pattern in the mixed mode 0 = sequential … [See Man Page]'
complete -c sctp_test -s d --description '0 = none 1 = min(default) 2 = max.'
complete -c sctp_test -s c --description '0 = 1 byte packets.  1 = 1352 byte packets.'
complete -c sctp_test -o ve --description 'Packets of specifed size.'
complete -c sctp_test -s m --description '(1500-65515, default value 32768).'
complete -c sctp_test -s H --description '.'
complete -c sctp_test -s P --description '.'
complete -c sctp_test -s h --description '.'
complete -c sctp_test -s p --description '.'
complete -c sctp_test -s x --description '.'
complete -c sctp_test -s o --description '0 = all unordered(default) 1 = all ordered 2 = … [See Man Page]'
complete -c sctp_test -s t --description ' 0 = sequential ascending(default)  1 = random.'
complete -c sctp_test -s M --description '(default value 0).'
complete -c sctp_test -s r --description '(default 0, use time()).'
complete -c sctp_test -s L --description '(default value 0).  Run the mixed mode.'
complete -c sctp_test -s S --description '(default value 0).  Run the mixed mode.'
complete -c sctp_test -s D --description 'Drain.  If in client mode do a read following send.'

