# shcomp
# Autogenerated from man page /usr/share/man/man1/shcomp.1.gz
# using Deroffing man parser
complete -c shcomp -s D -l dictionary --description 'Generate a list of strings that need to be plac… [See Man Page]'
complete -c shcomp -s n -l noexec --description 'Displays warning messages for obsolete or non-c… [See Man Page]'
complete -c shcomp -s v -l verbose --description 'Displays input from  infile onto standard error as it reads it.'
complete -c shcomp -l man --description 'Displays this man page on standard error and exits.'
complete -c shcomp -l help --description 'Shows a short help message and exits.  EXIT STATUS.'

