# stellarium
# Autogenerated from man page /usr/share/man/man1/stellarium.1.gz
# using Type1
complete -c stellarium -s v -l version --description 'Print program name and version and exit.'
complete -c stellarium -s h -l help --description 'Print a brief synopsis of program options and exit.'
complete -c stellarium -l safe-mode --description 'Do not use OpenGL2 features (such as shaders).'
complete -c stellarium -s c -l config-file --description 'Use file for the config filename instead of the default config.'
complete -c stellarium -s u -l user-dir --description 'Use dir instead of the default user data direct… [See Man Page]'
complete -c stellarium -s f -l full-screen --description 'With argument yes or no over-rides the full scr… [See Man Page]'
complete -c stellarium -l screenshot-dir --description 'Set the directory into which screenshots will b… [See Man Page]'
complete -c stellarium -l home-planet --description 'Specify observer planet.'
complete -c stellarium -l altitude --description 'Specify the initial observer altitude, where al… [See Man Page]'
complete -c stellarium -l longitude --description 'Specify the initial observer longitude, where l… [See Man Page]'
complete -c stellarium -l latitude --description 'Specify the initial observer latitude, where la… [See Man Page]'
complete -c stellarium -l list-landscapes --description 'Print a list of landscape names and exit.'
complete -c stellarium -l landscape --description 'Start Stellarium using landscape name.'
complete -c stellarium -l sky-date --description 'Specify sky date in format yyyymmdd.'
complete -c stellarium -l sky-time --description 'Specify sky time in format hh:mm:ss.'
complete -c stellarium -l fov --description 'Specify the field of view (fov degrees).'

