# stubmaker
# Autogenerated from man page /usr/share/man/man1/stubmaker.1p.gz
# using Type1
complete -c stubmaker -s d --description 'Specifies the directory you wish to output the files to.'
complete -c stubmaker -s v --description 'Turns on \\*(L"verbose\\*(R" output during the co… [See Man Page]'
complete -c stubmaker -l help --description 'Outputs a short help message.'

