# suspicious-source
# Autogenerated from man page /usr/share/man/man1/suspicious-source.1.gz
# using Deroffing man parser
complete -c suspicious-source -s h -l help --description 'Show this help message and exit.'
complete -c suspicious-source -s v -l verbose --description 'Print more information.'
complete -c suspicious-source -s d -l directory --description 'Check the files in the specified directory inst… [See Man Page]'
complete -c suspicious-source -s m -l mimetype --description 'Add mimetype to list of white-listed MIME types.'
complete -c suspicious-source -s e -l extension --description 'Add extension to list of white-listed extensions.'

