# synergyc
# Autogenerated from man page /usr/share/man/man1/synergyc.1.gz
# using Type1
complete -c synergyc -s d -l debug --description 'use debugging level level.'
complete -c synergyc -l display --description 'connect to the X server at display.'
complete -c synergyc -l daemon --description 'run the client as a daemon.'
complete -c synergyc -s f -l no-daemon --description 'run in client the foreground.'
complete -c synergyc -s n -l name --description 'use screen-name instead of  the hostname.'
complete -c synergyc -l restart --description 'restart the client automatically if it fails.'
complete -c synergyc -s 1 -l no-restart --description 'do not try to restart the client if it fails for some  reason.'
complete -c synergyc -s h -l help --description 'display help and exit.'
complete -c synergyc -l version --description 'display version information and exit.'

