# tftopl
# Autogenerated from man page /usr/share/man/man1/tftopl.1.gz
# using Deroffing man parser
complete -c tftopl -o charcode-format --description 'The argument  format specifies how character co… [See Man Page]'
complete -c tftopl -o verbose --description 'Without this option, tftopl operates silently.'

