# trickle
# Autogenerated from man page /usr/share/man/man1/trickle.1.gz
# using Darwin man parser
complete -c trickle -s h --description 'Displays help.'
complete -c trickle -s v --description 'Increases the verbosity level (can be specified… [See Man Page]'
complete -c trickle -s V --description 'Prints version.'
complete -c trickle -s s --description 'Runs trickle in standalone mode, independent of trickled 8.'
complete -c trickle -s d --description 'Limit the download bandwidth consumption to rate KB/s.'
complete -c trickle -s u --description 'Limit the upload bandwidth consumption to rate KB/s.'
complete -c trickle -s w --description 'Set peak detection window size to length KB.'
complete -c trickle -s t --description 'Set smoothing time to seconds s.'
complete -c trickle -s l --description 'Set smoothing length to length KB.'
complete -c trickle -s n --description 'Use trickled 8 socket path to communicate with trickled 8.'
complete -c trickle -s P --description 'Use the specified .'

