# unshar
# Autogenerated from man page /usr/share/man/man1/unshar.1.gz
# using Deroffing man parser
complete -c unshar -l version --description 'Print the version number of the program on stan… [See Man Page]'
complete -c unshar -l help --description 'Print a help summary on standard output, then i… [See Man Page]'
complete -c unshar -s d -l directory --description 'Change directory to DIRECTORY before unpacking any files.'
complete -c unshar -s c -l overwrite --description 'Passed as an option to the shar file.'
complete -c unshar -s e -l exit-0 --description 'This option exists mainly for people who collec… [See Man Page]'
complete -c unshar -s E -l split-at --description 'This option works like -e, but it allows you to… [See Man Page]'
complete -c unshar -s f -l force --description 'The same as -c.'

