# vftovp
# Autogenerated from man page /usr/share/man/man1/vftovp.1.gz
# using Deroffing man parser
complete -c vftovp -o charcode-format --description 'The argument  format specifies how character co… [See Man Page]'
complete -c vftovp -o verbose --description 'Without this option, vftovp operates silently.'

