# virtualenv
# Autogenerated from man page /usr/share/man/man1/virtualenv.1.gz
# using Deroffing man parser
complete -c virtualenv -s h -l help --description 'Show summary of options.'
complete -c virtualenv -l version --description 'Show the version of the program.'
complete -c virtualenv -s v -l verbose --description 'Be more verbose.'
complete -c virtualenv -s q -l quiet --description 'Be less verbose; suppress unimportant output.'
complete -c virtualenv -l clear --description 'Clear out a previously-created virtual Python i… [See Man Page]'
complete -c virtualenv -s p -l python --description 'The Python interpreter to use to create the new environment.'
complete -c virtualenv -l no-site-packages --description 'Ignored (the default).'
complete -c virtualenv -l system-site-packages --description 'Give access to the global site-packages modules… [See Man Page]'
complete -c virtualenv -l unzip-setuptools --description 'Unzip Setuptools or Distribute when installing it.'
complete -c virtualenv -l relocatable --description 'Make an EXISTING virtualenv environment relocatable.'
complete -c virtualenv -l distribute --description 'Ignored.   Distribute is used by default.'
complete -c virtualenv -l setuptools --description 'Use Setuptools instead of Distribute.'
complete -c virtualenv -l extra-search-dir --description 'Directory to search for setuptools/distribute/p… [See Man Page]'
complete -c virtualenv -l never-download --description 'Never download anything from the network.'
complete -c virtualenv -l prompt --description '.'

