# who-uploads
# Autogenerated from man page /usr/share/man/man1/who-uploads.1.gz
# using Deroffing man parser
complete -c who-uploads -s M -l max-uploads --description 'Specify the maximum number of uploads to displa… [See Man Page]'
complete -c who-uploads -l keyring --description 'Add keyring to the list of keyrings to be searc… [See Man Page]'
complete -c who-uploads -l no-default-keyrings --description 'By default, who-uploads uses the two Debian key… [See Man Page]'
complete -c who-uploads -l date --description 'Show the date of the upload alongside the uploader\'s details.'
complete -c who-uploads -l nodate -l no-date --description 'Do not show the date of the upload alongside th… [See Man Page]'
complete -c who-uploads -l no-conf -l noconf --description 'Do not read any configuration files.'
complete -c who-uploads -l help -s h --description 'Display a help message and exit successfully.'
complete -c who-uploads -l version --description 'Display version and copyright information and e… [See Man Page]'

