# whodepends
# Autogenerated from man page /usr/share/man/man1/whodepends.1.gz
# using Deroffing man parser
complete -c whodepends -l help -s h --description 'Show a brief usage message.'
complete -c whodepends -l version -s v --description 'Show version and copyright information.'

