# wnpp-check
# Autogenerated from man page /usr/share/man/man1/wnpp-check.1.gz
# using Deroffing man parser
complete -c wnpp-check -l help -s h --description 'Show a summary of options.'
complete -c wnpp-check -l version -s v --description 'Show version and copyright information.  SEE ALSO http://www.'

