# wrap-and-sort
# Autogenerated from man page /usr/share/man/man1/wrap-and-sort.1.gz
# using Deroffing man parser
complete -c wrap-and-sort -s h -l help --description 'Show this help message and exit.'
complete -c wrap-and-sort -s a -l wrap-always --description 'Wrap all package lists in the Debian control fi… [See Man Page]'
complete -c wrap-and-sort -s s -l short-indent --description 'Only indent wrapped lines by one space (default… [See Man Page]'
complete -c wrap-and-sort -s b -l sort-binary-packages --description 'Sort binary package paragraphs by name.'
complete -c wrap-and-sort -s k -l keep-first --description 'When sorting binary package paragraphs, leave t… [See Man Page]'
complete -c wrap-and-sort -s n -l no-cleanup --description 'Do not remove trailing whitespaces.'
complete -c wrap-and-sort -s d -l debian-directory --description 'Location of the debian directory (default: . /debian).'
complete -c wrap-and-sort -s f -l file --description 'Wrap and sort only the specified file.'
complete -c wrap-and-sort -s v -l verbose --description 'Print all files that are touched.'

