# wsdl2
# Autogenerated from man page /usr/share/man/man1/wsdl2.1.gz
# using Deroffing man parser
complete -c wsdl2 -o appsettingurlkey:key -o urlkey:key --description 'Specifies that the url for the services should … [See Man Page]'
complete -c wsdl2 -o appsettingbaseurl:url -o baseurl:url --description 'Specifies a base URL for the service.'
complete -c wsdl2 -o language:language -s l --description 'Language of the code to generate.'
complete -c wsdl2 -o namespace:name -o n:name --description 'The namespace of the generated classes.'
complete -c wsdl2 -o out:filename -o o:filename --description 'The target file for generated code.'
complete -c wsdl2 -o protocol:protocol -o p:protocol --description 'The protocol for which to generate code.'
complete -c wsdl2 -o sample:METHOD --description 'This will display XML request and reply of the … [See Man Page]'
complete -c wsdl2 -o server --description 'Generate a server skeleton instead of a client proxy.'
complete -c wsdl2 -o nologo --description 'Supress the startup logo.'
complete -c wsdl2 -o u:username -o user:username --description 'The user name to use when connecting to the server.'
complete -c wsdl2 -o p:password -o password:password --description 'The password to use when connecting to the server.'
complete -c wsdl2 -o appsettingurlkey --description 'option, and the .'
complete -c wsdl2 -o type:typename --description 'Generate a proxy for a compiled web service class.'
complete -c wsdl2 -o d:domain -o domain:domain --description 'The domain to use when connecting to the server.'

