// Generated by CoffeeScript 1.3.3
(function() {
    "use strict";

    var chrome, cmd, fb, firebug, global, __slice = [].slice;

    global = window;

    fb = global.Firebug;

    chrome = fb.chrome;

    cmd = fb.CommandLine;

    firebug = {
        info: {
            version: '0.1.3',
            open: "open firebug window",
            close: "minimize firebug window",
            toggle: "toggle firebug window",
            disable: "exit from firebug",
            console: "open console and set focus",
            multiline: "multiline console",
            "toggle-console": "toggle between one-line and multiline console",
            clear: "clear console output window",
            run: "run script that was entered in console editor",
            'tab': "focuses the specified firebug tab (console, html, stylesheet, script, dom, net, etc)",
            'tab-side': "focuses the specified firebug side tab (css, computed, layout, dom, domSide, watch)",
            'tab-right': "focuses the next firebug tab(right)",
            'tab-left': "focuses the next firebug tab(left)",
            '#': "focuses the prev firebug tab",
            'search': "search",
            inspect: "toggle the firebug element inspector",
            behave: "use Behave.js for console (like auto-pairs)"
        },
        open: function() {
            if (!chrome.isOpen()) {
                return fb.toggleBar(true, 'console');
            }
        },
        close: function() {
            if (chrome.isOpen()) {
                return fb.toggleBar();
            }
        },
        toggle: function() {
            return fb.toggleBar();
        },
        disable: function() {
            return fb.closeFirebug(true);
        },
        inspect: function() {
            if (!fb.currentContext) {
                fb.toggleBar(true);
            }
            return fb.Inspector.toggleInspecting(fb.currentContext);
        },
        behave: function() {
            if (this._editor) {
                this._editor.destroy();
                this._editor = null;
                return;
            }
            if (!this._editor && cmd && dactyl.plugins && dactyl.plugins.Behave) {
                return this._editor = new dactyl.plugins.Behave({
                    textarea: cmd.getCommandEditor().editor.textBox
                });
            }
        },
        console: function() {
            var cmEditor, cmLine;
            if (!chrome.isOpen()) {
                this.open();
            }
            chrome.switchToPanel(fb.currentContext, "console");
            cmLine = cmd.getSingleRowCommandLine();
            cmEditor = cmd.getCommandEditor();
            if (fb.commandEditor) {
                if (cmEditor.focus) {
                    return cmEditor.focus();
                } else {
                    return cmEditor.select();
                }
            } else {
                return cmLine.select();
            }
        },
        multiline: function() {
            if (chrome.isOpen()) {
                return cmd.toggleMultiLine(true);
            }
        },
        "toggle-console": function() {
            if (chrome.isOpen()) {
                return cmd.toggleMultiLine();
            }
        },
        clear: function() {
            if (chrome.isOpen()) {
                return fb.Console.clear();
            }
        },
        run: function() {
            if (chrome.isOpen()) {
                return cmd.enter(fb.currentContext);
            }
        },
        'tab': function(panelName) {
            if (panelName == null) {
                panelName = "console";
            }
            if (chrome.isOpen()) {
                return chrome.navigate(null, panelName);
            }
        },
        'tab-side': function(panelName) {
            if (chrome.isOpen()) {
                return chrome.selectSidePanel(panelName);
            }
        },
        'tab-right': function() {
            if (chrome.isOpen()) {
                return chrome.gotoSiblingTab(true);
            }
        },
        'tab-left': function() {
            if (chrome.isOpen()) {
                return chrome.gotoSiblingTab();
            }
        },
        '#': function() {
            if (chrome.isOpen()) {
                return chrome.gotoPreviousTab();
            }
        },
        'search': function() {
            var text;
            text = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            if (chrome.isOpen()) {
                fb.Search.focus(fb.currentContext);
                return fb.Search.search(text.join(' '), fb.currentContext);
            }
        },
        'mode': function() {
            modes.push(modes.FIREBUG);
            if (!chrome.isOpen()) {
                return fb.toggleBar(true, 'console');
            }
        },
        _initialize: function() {
            fb = global.Firebug;
            chrome = fb.chrome;
            cmd = fb.CommandLine;
            return this.behave();
        }
    };

    function simulateKeyEvent(panel, keycode) {
        function hasClass(el, name){
            return el.className.split(" ").indexOf(name) != -1;
        }
        var el, evt, canceled;
        evt = global.Firebug.chrome.window.document.createEvent("KeyboardEvent");
        evt.initKeyEvent("keypress", true, true, null,
                0, 0, 0, 0,
                keycode, 0);

        if(panel.document.activeElement){
            el = panel.document.activeElement;
            if (panel.name == "stylesheet"){
                if(!hasClass(el, "cssProp") && !hasClass(el, "cssHead")){
                    var els = panel.panelNode.getElementsByClassName("cssProp");
                    if(els.length > 1){
                        el = els[0];
                    }
                }
            } else {
                if(el.getAttribute("role") == "DOM Panel"){
                    var els = panel.panelNode.getElementsByClassName("a11yFocus");
                    if(els.length > 1){
                        el = els[0];
                    }
                }
            }
        } else {
            el = panel.panelNode;
        }
        el.dispatchEvent(evt);
    }

    group.commands.add(['firebug', 'fbpc'], "firebug-pentadactyl (version " + firebug.info.version + ")", function(args) {
        var command, index, _i, _len, _results;
        if (!chrome) {
            firebug._initialize();
        }
        _results = [];
        for (index = _i = 0, _len = args.length; _i < _len; index = ++_i) {
            command = args[index];
            if (firebug[command]) {
                _results.push(firebug[command].apply(firebug, args.slice(index + 1)));
            }
        }
        return _results;
    }, {
        completer: function(context) {
            var name;
            return context.completions = (function() {
                var _results;
                _results = [];
                for (name in firebug) {
                    if (name !== 'info' || name.indexOf('_')) {
                        _results.push([name, firebug.info[name]]);
                    }
                }
                return _results;
            })();
        }
    });

    group.options.add(["fbliverun"], "run script on blur firebug console", "boolean", false, {
        setter: function(value) {
            var cmEditor;
            if (!cmd) {
                firebug._initialize();
            }
            cmEditor = cmd.getCommandEditor();
            if (value) {
                return cmEditor.editor.addEventListener('blur', firebug.run);
            } else if (!value) {
                return cmEditor.editor.removeEventListener('blur', firebug.run);
            }
        }
    });

    modes.addMode("FIREBUG", {
        extended: true,
        description: "firebug",
        bases: [modes.COMMAND],
        input: false,
    });

    group.mappings.add([modes.FIREBUG], ["i"],
            "Leave Autocomplete or Menu mode",
    function () { 
        var panel = global.Firebug.chrome.getSelectedPanel();
        if(panel.name == "html"){
            modes.push(modes.INSERT);
            panel.editNode(panel.selection);
        } else if(panel.name == "stylesheet"){
            modes.push(modes.INSERT);
            simulateKeyEvent(panel, 13);
        } else if(panel.name == "dom"){
            modes.push(modes.INSERT);
            panel.editProperty(panel.document.activeElement.parentElement.parentElement);
        } else {
            firebug.console();
        }
    });

    group.mappings.add([modes.FIREBUG], ["d"],
            "Leave Autocomplete or Menu mode",
        function () { 
            var panel = global.Firebug.chrome.getSelectedPanel();
            panel.deleteNode(panel.selection);

        });

    group.mappings.add([modes.FIREBUG], ["/"],
            "Leave Autocomplete or Menu mode",
    function () { 
        firebug.search();
    });

    var tabs = [
        "console", "html", "stylesheet", "script", "dom", "net", "cookies"
        ];
    group.mappings.add([modes.FIREBUG], ["b"],
            "",
    function ({count}) { 
        if (count > tabs.length)
            return;
        firebug.tab(tabs[count-1]);
    }, {count: true});

    group.mappings.add([modes.FIREBUG], ["gt"],
            "Leave Autocomplete or Menu mode",
    function () { 
        firebug["tab-right"]();
    });
    group.mappings.add([modes.FIREBUG], ["gT"],
            "Leave Autocomplete or Menu mode",
    function () { 
        firebug["tab-left"]();
    });

    var addTabSideMapping = function (key, maps){
        group.mappings.add([modes.FIREBUG], [key],
            "",
            function(){
                var panel = global.Firebug.chrome.getSelectedPanel();
                if(maps[panel.name]){
                    firebug["tab-side"](maps[panel.name]);
                }
        });
    }
    addTabSideMapping("gs", {"html": "css", "script": "callstack"});
    addTabSideMapping("gc", {"html": "computed"});
    addTabSideMapping("gl", {"html": "layout"});
    addTabSideMapping("gd", {"html": "domSide"});
    addTabSideMapping("gw", {"script": "watches"});
    addTabSideMapping("gb", {"script": "breakpoints"});

    group.mappings.add([modes.FIREBUG], ["q"],
            "Leave Autocomplete or Menu mode",
    function () { 
        modes.pop();
        firebug.disable();
    });


    var addMovementMapping = function(key, dir, keycode){
        group.mappings.add([modes.FIREBUG], [key],
                "Leave Autocomplete or Menu mode",
                function(){
                    var panel = global.Firebug.chrome.getSelectedPanel();
                    simulateKeyEvent(panel, keycode);
                });
    };

    addMovementMapping("h", "left", 37);
    addMovementMapping("j", "down", 40);
    addMovementMapping("k", "up", 38);
    addMovementMapping("l", "right", 39);
    addMovementMapping("<C-d>", "page down", 34);
    addMovementMapping("<C-u>", "page up", 33);
    addMovementMapping("gg", "home", 36);
    addMovementMapping("G", "end", 35);

}).call(this);
